import { outputTokenName } from './comparison.js';
import type { ForwardProgress } from '../worker/protocol.js';
import type { SpatialReadModel } from "./bindings.js";
import type { Address, Explanation } from "./forward.js";
import { operations, parameterOwners } from "./forward.js";
import { geometry, projection } from "./view.js";
import { probabilityColor, project3 } from "./geometry.js";
import { simplexGlyph } from "./scene.js";
import { escapeHtml as esc } from "../views/evidence.js";
import { sourceView } from "../source/catalog.js";
export const fmt=(value:number|undefined)=>value===undefined?"unavailable":Number(value.toPrecision(7)).toString();
const val=(v:number|undefined)=>`<span data-value="${v??""}" title="${v??"unavailable"}">${fmt(v)}</span>`;
export const addressLabel=(a:Address)=>`${operations.find(o=>o.kind===a.kind)?.title??a.kind}${a.layer===undefined?"":` · L${a.layer}`} · p${a.token}${a.head===undefined?"":` / h${a.head}`}`;
function valuesTable(e:Explanation, vocabulary?:readonly string[]) {
  return `<div class="element-grid" data-testid="forward-elements">${e.output?.map((v,i)=>`<button data-forward-element="${i}" data-value="${v}" title="${v}"><small>${vocabulary?esc(outputTokenName(i,vocabulary))+" · ":""}[${i}]</small>${fmt(v)}</button>`).join("")??"<p>NOT CAPTURED · no substituted values.</p>"}</div>`;
}
function arithmetic(e:Explanation, element:number) {
  const family=e.definition?.family;
  if(!e.indexValid) return '<p role="status">Element unavailable in this source. Select a valid component; the prior scalar is not rebound.</p>';
  if(family==="linear") return `<p>Output[${element}] ≈ Σ input[j] × W[${element},j]. Rows are outputs, columns are inputs; no bias.</p><div class="table-scroll"><table data-testid="linear-terms"><thead><tr><th>j</th><th>Input</th><th>Weight</th><th>Product · derived</th></tr></thead><tbody>${e.terms?.map(t=>`<tr><th>${t.index}</th><td>${val(t.input)}</td><td>${val(t.weight)}</td><td>${val(t.product)}</td></tr>`).join("")??"<tr><td>Checkpoint unavailable</td></tr>"}</tbody></table></div><p>Derived sum ${val(e.terms?.reduce((s,t)=>s+t.product,0))} ≈ observed ${val(e.observed)}</p>`;
  if(family==="norm") return `<p>All ${e.inputs?.length} input components contribute to mean(x²). The shared scale preserves the direction while controlling magnitude.</p><p>Derived mean square = ${val(e.meanSquare)}<br>Scale = (mean(x²) + 0.00001)<sup>−½</sup> ≈ ${val(e.normScale)}</p><p>x[${element}] × scale ≈ ${val(e.inputs?.[element])} × ${val(e.normScale)} ≈ ${val(e.observed)} observed</p>`;
  if(family==="add") return `<p>Matching components are added; neither operand is a mixture or a concatenation.</p><p>${val(e.pairs?.[0])} + ${val(e.pairs?.[1])} ≈ ${val(e.observed)} observed</p>`;
  if(family==="scale") return `<p data-testid="composite-scale-calculation">The adapter output is multiplied by the immutable definition constant; s is not an optimizer parameter.</p><p>${val(e.inputs?.[element])} × ${val(e.fixedScale)} = ${val(e.observed)} observed</p>`;
  if(family==="constant") return `<p>Fixed model-definition constant ${val(e.fixedScale)}. This declaration is source-owned and has no observed tensor artifact or optimizer state.</p>`;
  if(family==="lookup") return `<p>Token/position ID selects checkpoint row ${e.lookupRow}. Lookup returns the stored scalar unchanged.</p><p>${e.definition?.parameter}[${e.lookupRow},${element}] = ${val(e.parameter?.[e.lookupRow]?.[element])} → ${val(e.observed)} observed</p>`;
  if(family==="relu") return e.address.kind==='mlpLeakyRelu'
    ?`<p data-testid="leaky-relu-calculation">Leaky ReLU[${element}] = x when x &gt; 0, otherwise 0.01 × x: ${val(e.before)} → ${val(e.observed)} observed.<br>Local derivative = ${val(e.derivative)}; the declared zero convention is 0.01.</p><p>All ${e.output?.length} hidden components remain above; the actual scalar operation preserves a scaled negative branch.</p>`
    :`<p data-testid="relu-calculation">ReLU[${element}] = max(0, ${val(e.before)}) = ${val(e.observed)} observed.<br>Local derivative = ${val(e.derivative)} (the model uses 0 at zero).</p><p>All ${e.output?.length} hidden components remain above; ReLU acts on original components, not projected geometry.</p>`;
  if(family==="concat") return `<p>Output component ${element} comes from head ${Math.floor(element/e.headWidth)}, component ${element%e.headWidth}. ${Array.from({length:e.heads},(_,h)=>`Head ${h} occupies [${h*e.headWidth},${(h+1)*e.headWidth})`).join("; ")}. This copies channels; no addition or normalization.</p><p>Observed concatenated component ${val(e.observed)}</p>`;
  if(family==="softmax") return `<p>Every available logit enters the same denominator. The selected scalar alone does not produce the row.</p><p>Derived stable maximum = ${val(e.maximum)} · sum exp(score − max) = ${val(e.denominator)}</p><div class="table-scroll"><table data-testid="softmax-terms"><thead><tr><th>Index</th><th>Observed score</th><th>score − max</th><th>exp · derived</th><th>Observed P</th></tr></thead><tbody>${e.scoreInputs?.map((v,i)=>`<tr><th>${i}</th><td>${val(v)}</td><td>${val(v-e.maximum!)}</td><td>${val(e.exponentials?.[i])}</td><td>${val(e.output?.[i])}</td></tr>`).join("")}</tbody></table></div><p>exp[${element}] / shared sum ≈ ${val(e.exponentials?.[element])} / ${val(e.denominator)} ≈ ${val(e.observed)} observed</p>`;
  return "";
}
export function mixture(e:Explanation,element:number) {
  const g=e.mixture;if(!g)return "<p>Mixture unavailable · complete V vectors and weights are required.</p>";
  const projected=g.coordinates.map(project3),p=project3(g.point);
  const extent=Math.max(...projected.flatMap(v=>v.map(Math.abs)),0),scale=extent===0?1:120/extent;
  const xy=(v:readonly number[])=>`${175+v[0]*scale},${155+v[1]*scale}`;
  return `<p data-testid="mixture-rank">${esc(g.description)}</p><p>Origin = V at key 0. Fixed oblique linear screen projection of the declared 3D coordinates. Screen geometry is a display transform; screen distances and angles may be distorted; original-space values/arithmetic remain authoritative.</p><svg class="mixture-geometry" viewBox="0 0 350 310" aria-label="Actual value contributors and weighted affine mixture">${projected.map(v=>`<path d="M${xy(v)} L${xy(p)}"/>`).join("")}${projected.map((v,i)=>`<circle data-mixture-key="${i}" data-coordinates="${g.coordinates[i].join(",")}" cx="${175+v[0]*scale}" cy="${155+v[1]*scale}" r="5"/><text x="${182+v[0]*scale}" y="${148+v[1]*scale}">${i}</text>`).join("")}<circle class="barycenter" data-testid="mixture-point" data-coordinates="${g.point.join(",")}" cx="${175+p[0]*scale}" cy="${155+p[1]*scale}" r="7"/></svg><div class="table-scroll"><table data-testid="mixture-contributors"><thead><tr><th>Key</th><th>Observed α</th><th>Complete V head vector</th><th>α × V[${element}]</th></tr></thead><tbody>${e.points!.map((v,i)=>`<tr><th>${i}</th><td>${val(e.probabilities?.[i])}</td><td>[${v!.map(fmt).join(", ")}]</td><td>${val(e.probabilities![i]*v![element])}</td></tr>`).join("")}</tbody></table></div>${e.zeroed?`<p>Derived reconstruction[${element}] ≈ ${val(g.mixture[element])} · observed treatment output ${val(e.observed)} (replaced by zero)</p>`:`<p>Original-space sum[${element}] ≈ ${val(g.mixture[element])} · observed ${val(e.observed)}</p>`}`;
}
export function forwardInspector(m:SpatialReadModel,address:Address,element:number,parameter:string|undefined,row:number,column:number,scalar:string,execution?:ForwardProgress, sceneOpen=false) {
  const executing=!!execution;
  const f=m.forward,e=f.explain(address,element);
  const chosen=parameter??addressLabel(address);
  const owner=parameter?f.parameterOwners[parameter]:undefined;
  const links=(direction:"upstream"|"downstream")=>(parameter?direction==="upstream"?[]:[{address:{kind:owner?.kind??parameterOwners[parameter],token:address.token,...(owner?.layer===undefined?{}:{layer:owner.layer})},port:"parameter owner",type:"parameter"}]:e[direction]).map(d=>`<button data-dependency="${esc(JSON.stringify(d.address))}">${esc(addressLabel(d.address))}<small>${esc(d.port)} · ${esc(d.type)}</small></button>`).join("")||"<p>No captured forward dependency in this direction.</p>";
  let content="";
  if(parameter){
    const matrix=f.matrix(parameter),rows=matrix?.length??0,cols=matrix?.[0]?.length??0;
    const detail=f.parameterDetails[parameter];
    const option=(n:number,selected:number)=>`${selected>=n?`<option selected value="${selected}">${selected} unavailable</option>`:""}${Array.from({length:n},(_,i)=>`<option value="${i}" ${i===selected?"selected":""}>${i}</option>`).join("")}`;
    content=`<h3>Persistent checkpoint matrix · ${rows} × ${cols}</h3><p data-testid="parameter-ownership">Definition <code>${esc(detail?.definition??f.descriptor.modelDefinition)}</code> · owner <code>${esc(detail?.owner?.kind??'unresolved')}</code> · <strong>${esc(detail?.trainability??'unknown')}</strong> · optimizer ${detail?.optimizerMembership===true?'member':detail?.optimizerMembership===false?'not a member':'definition default'}<br>Shape [${rows}, ${cols}] · axes ${esc(detail?.axes?.join(' × ')??'unavailable')} · input basis <code>${esc(detail?.inputBasis??'unavailable')}</code> · output basis <code>${esc(detail?.outputBasis??'unavailable')}</code> · ${esc(detail?.dtype??'unknown')}</p><p>Bound to <code>${esc(f.sourceSnapshotId??"unavailable")}</code> · ${esc(f.parameterProvenance)}</p><div class="controls"><label>Output / lookup row<select id="parameter-row">${option(rows,row)}</select></label><label>Input column<select id="parameter-column">${option(cols,column)}</select></label></div><p>${esc(parameter)}[${row},${column}] = ${val(matrix?.[row]?.[column])}</p><div class="table-scroll"><table data-testid="parameter-matrix"><tbody>${matrix?.map((r,i)=>`<tr><th>${i}</th>${r.map((v,j)=>`<td><button data-parameter-cell="${i},${j}" data-value="${v}" title="${v}">${fmt(v)}</button></td>`).join("")}</tr>`).join("")??"unavailable"}</tbody></table></div><button id="parameter-output">Follow this row to its output / scalar operands</button><p>Observed execution values and pinned source-derived parameter structure remain separately classified.</p>`;
  }else{
    const calculation=e.zeroed?'Declared intervention: aggregated head output replaced with constant zero before concatenation':e.definition?.family==='linear'?`Σ input[j] × W[${element},j] = ${fmt(e.terms?.reduce((sum,t)=>sum+t.product,0))}`:
      e.definition?.family==='norm'?`${fmt(e.inputs?.[element])} × (mean square ${fmt(e.meanSquare)} + 0.00001)⁻½`:
      e.definition?.family==='add'?`${e.pairs?.map(fmt).join(' + ')}`:
      e.definition?.family==='scale'?`${fmt(e.inputs?.[element])} × fixed s ${fmt(e.fixedScale)}`:
      e.definition?.family==='constant'?`fixed definition constant s = ${fmt(e.fixedScale)}`:
      e.definition?.family==='lookup'?`${e.definition.parameter}[${e.lookupRow},${element}] = ${fmt(e.parameter?.[e.lookupRow]?.[element])}`:
      e.definition?.family==='relu'?(address.kind==='mlpLeakyRelu'?`${fmt(e.before)} > 0 ? x : 0.01 × x`:`max(0, ${fmt(e.before)})`):
      e.definition?.family==='softmax'?`exp(${fmt(e.scoreInputs?.[element])} − ${fmt(e.maximum)}) / ${fmt(e.denominator)}`:
      e.definition?.family==='score'?`Σ Q[j] × K[j] = ${fmt(m.geometry?.dot)}; divide by √${m.width}`:
      e.definition?.family==='mixture'?(e.zeroed?`Derived reconstruction: Σ α[key] × V[key,${element}] = ${fmt(e.derivedReconstruction)} → declared constant output = 0`:`Σ α[key] × V[key,${element}] = ${fmt(e.mixture?.mixture[element])}`):
      `Copy head ${Math.floor(element/e.headWidth)}, channel ${element%e.headWidth} into concatenated channel ${element}`;
    const outputView=['logits','probabilities'].includes(address.kind);
    const probabilities=f.values({kind:'probabilities',token:address.token});
    const highest=probabilities?.reduce((best,v,i)=>v>probabilities[best]?i:best,0);
    const prediction=outputView?`<p data-testid="prediction-summary">Position ${address.token} · target ${f.targets[address.token]===undefined?'not recorded for this inference witness':esc(outputTokenName(f.targets[address.token],f.vocabulary))}. Highest-probability token: ${highest===undefined?'pending':esc(outputTokenName(highest,f.vocabulary))+' · '+val(probabilities?.[highest])}. Inspected component: ${esc(outputTokenName(element,f.vocabulary))} [${element}]${address.kind==='logits'?' · logit':' · probability'}.</p>`:'';
    const inputs=e.upstream.map(d=>addressLabel(d.address)).join(', ');
    const next=e.downstream.map(d=>addressLabel(d.address)).slice(0,4).join(', ')||'prediction readout';
    content=`${prediction}<p data-testid="semantic-address"><code>${esc(e.semanticId)}</code></p><section class="teaching-step" data-testid="teaching-step"><p><b>Inputs</b> ${esc(inputs||'captured token / position ID')}</p><p><b>Calculation</b> ${esc(calculation)}. ${esc(e.definition?.purpose??'')}</p><p><b>Result</b> Component [${element}] = ${val(e.observed)}. Next consumer: ${esc(next)}.</p></section><details open><summary>Calculation and complete values</summary><p>Observed artifact <code data-testid="forward-artifact">${esc(e.artifact?.id??"NOT CAPTURED")}</code> · layer ${address.layer??'model'} · position ${address.token}${address.head===undefined?"":` / head ${address.head}`}</p><h3>All ${e.output?.length??0} components · selected [${element}]</h3>${valuesTable(e,outputView?f.vocabulary:undefined)}<p>Observed selected output ${val(e.observed)} ${e.indexValid?`<button data-artifact="${esc(e.artifact!.id)}" data-element="${element}">Inspect selected scalar</button>`:""}</p>
      ${address.kind==="attentionLogits"?`${sceneOpen?"":geometry(m)}<table data-testid="qk-products"><thead><tr><th>j</th><th>Q</th><th>K</th><th>Q × K</th></tr></thead><tbody>${m.lens?.q?.map((q,j)=>`<tr><th>${j}</th><td>${val(q)}</td><td>${val(m.lens?.k?.[j])}</td><td>${val(m.lens?.k?.[j]===undefined?undefined:q*m.lens.k[j])}</td></tr>`).join('')??''}</tbody></table><p>Σ component products = ${val(m.geometry?.dot)}; divide by √${m.width} = ${val(m.lens?.scaled)} → observed selected score ${val(e.observed)} in the complete causal row above.</p><details><summary>Complete vector values and artifact sources</summary><p>Q [${m.lens?.q?.map(fmt).join(", ")??"unavailable"}]</p><p>K [${m.lens?.k?.map(fmt).join(", ")??"unavailable"}]</p><p>Q <code data-testid="spatial-q-artifact">${esc(m.q?.id??"unavailable")}</code><br>Score <code data-testid="spatial-score-artifact">${esc(m.heads[m.selection.head]?.scores?.id??"unavailable")}</code></p></details><h3>Complete causal score inputs</h3><p>All ${e.output?.length??0} observed scores above feed softmax. ${m.selection.key>m.selection.query?`Key ${m.selection.key} is in the future and has no causal score.`:`Selected key ${m.selection.key} is available.`}</p><h3>Q projection · source row</h3>${projection(m)}`:""}
      ${['attentionLogits','headOutput'].includes(address.kind)?'<p>Earlier-position K/V are already available context from this completed run; the explanation does not execute them.</p>':''}${arithmetic(e,element)}${address.kind==="headOutput"?e.zeroed?`<div data-testid="zeroed-head-arithmetic"><p>Intervention site · declared head ablation replaces selected head output with explicit numerical zeros before concatenation. Q/K/V and attention weights were still computed. The zero has no backward training path in this read-only experiment.</p><div class="table-scroll"><table data-testid="pre-ablation-provenance"><thead><tr><th>Evidence</th><th>Class</th><th>Artifact / Source</th><th>Selected [${element}]</th></tr></thead><tbody><tr><td>Attention probabilities (α)</td><td><span class="evidence-tag tag-observed">OBSERVED</span></td><td><code>${esc(e.probabilities?(f.artifact({kind:'attentionProbabilities',token:address.token,layer:address.layer,head:address.head})?.id??'available'):'unavailable')}</code></td><td>${val(e.probabilities?.[m.selection.key])} <small>(key ${m.selection.key})</small></td></tr><tr><td>V head vectors</td><td><span class="evidence-tag tag-observed">OBSERVED</span></td><td><code>${esc(f.artifact({kind:'v',token:m.selection.key,layer:address.layer})?.id??'available')}</code></td><td>${val(e.points?.[m.selection.key]?.[element])} <small>(key ${m.selection.key})</small></td></tr><tr><td>Derived Σ αV reconstruction</td><td><span class="evidence-tag tag-derived">DERIVED</span></td><td>reconstructed from observed α and V vectors</td><td data-testid="derived-reconstruction-value">${val(e.derivedReconstruction)}</td></tr><tr><td>headOutputBeforeAblation</td><td><span class="evidence-tag tag-observed">OBSERVED</span></td><td><code data-testid="pre-ablation-artifact">${esc(e.preAblationArtifact?.id??'UNAVAILABLE')}</code></td><td data-testid="pre-ablation-observed-value">${e.preAblationObserved!==undefined?val(e.preAblationObserved):'unavailable'}</td></tr><tr><td>replacement-zero headOutput</td><td><span class="evidence-tag tag-observed">OBSERVED treatment result</span></td><td><code data-testid="zeroed-output-artifact">${esc(e.artifact?.id??'available')}</code></td><td data-testid="zeroed-output-value">${val(e.observed)}</td></tr></tbody></table></div><p data-testid="pre-ablation-verification">${e.preAblationVerification?.status==='verified'?`Verification: derived Σ αV reconstruction (DERIVED) matches observed pre-ablation artifact (OBSERVED) within canonical float64 policy.`:e.preAblationVerification?.status==='mismatch'?`Verification failed: derived reconstruction differs from observed pre-ablation artifact.`:e.preAblationVerification?.message??'Actual pre-ablation observation is unavailable in this recording; derived reconstruction remains available as DERIVED evidence.'}</p></div>`:sceneOpen?"<p>Affine geometry is open beside the selected world operation.</p>":mixture(e,element):""}
      ${e.simplex?`<svg class="output-simplex" viewBox="0 0 360 290" aria-label="Probability tetrahedron with calculated barycenter">${simplexGlyph(e.simplex.vertices,e.simplex.point,180,145,76,Array.from({length:e.output?.length??0},(_,i)=>outputTokenName(i,f.vocabulary)))}</svg><p>Regular 3D tetrahedron, fixed oblique linear screen projection. Screen geometry is a display transform; screen distances and angles may be distorted; original-space values/arithmetic remain authoritative. Vertex IDs: ${m.labels.length?"0=a, 1=b, 2=c, 3=END (input START shares ID 3)":""}. Point = Σ probability × vertex.</p>`:""}
      ${address.kind==="attentionLogits"||address.kind==="attentionProbabilities"?`<h3>Causal scope · query ${address.token}, all ${f.input.length} positions</h3><div class="causal-row">${f.input.map((_,i)=>`<button data-spatial-key="${i}" ${i===m.selection.key?'aria-pressed="true"':""} style="--probability:${probabilityColor(f.values({kind:"attentionProbabilities",token:address.token,head:address.head})?.[i])}">${i}<br>${i>address.token?"future · NA":fmt(f.values({kind:"attentionProbabilities",token:address.token,head:address.head})?.[i])}</button>`).join("")}</div>`:""}
      <details><summary>Read operation source</summary>${sourceView(address.kind)}</details></details>`;
  }
  if(executing&&!parameter&&!e.artifact&&f.executionState(address,execution)==='pending') content=`<section data-testid="pending-output"><h3>Not yet computed</h3><p>${esc(addressLabel(address))} has no produced output. Inspection and navigation grant no permits. Use Next operator or Continue to advance the execution frontier.</p>${address.kind==='attentionLogits'&&m.selection.key>address.token?'<p>Future causal key · NOT APPLICABLE (no edge exists).</p>':''}</section>`;
  if(executing) content=content.replace('Earlier-position K/V are already available context from this completed run; the explanation does not execute them.','Earlier positions execute first; only already produced K/V can participate. Inspection grants no permits.');
  return `<div class="lens-heading"><div><small>SELECTED WORLD OBJECT</small><h2>${esc(chosen)}</h2></div><button id="close-spatial-lens" aria-label="Close arithmetic lens">×</button></div><div class="lens-context"><span>${executing?'ACTIVE EXECUTION':esc(m.source.relationship)} · ${esc(m.source.capturedDocument)}</span><button id="lens-home">Home</button><button id="lens-back">Back</button></div><div class="lens-scroll" data-scroll-region="spatial-lens">${content}<section class="dependency-choices"><h3>Upstream · choose an operand</h3><div data-testid="upstream-choices">${links("upstream")}</div><h3>Downstream · choose a consumer</h3><div data-testid="downstream-choices">${links("downstream")}</div></section><section class="spatial-scalar" id="microscope"><h3>Scalar / source inspection</h3>${scalar}</section><details><summary>Bound run, checkpoint and runtime</summary><footer><p>Run <code data-testid="spatial-run">${esc(m.source.sourceRunId)}</code><br>Snapshot <code data-testid="spatial-snapshot">${esc(m.source.sourceSnapshotId??"unavailable")}</code><br>Runtime <code data-testid="spatial-runtime">${esc(m.runtime)}</code></p></footer></details></div>`;
}
