import type {LearningModel,LearningStage,ParameterPin} from './learning.js';
import type {Address} from './forward.js';
import {escapeHtml as esc} from '../views/evidence.js';
import {reticle,stationFor} from './scene.js';
export const parameterLabel=(p:ParameterPin)=>`${p.name}[${p.row},${p.column}]`;
const number=(v:number|undefined)=>v===undefined?'unavailable':v===Infinity?'∞ (zero target probability)':Number(v.toPrecision(8)).toString();
const val=(v:number|undefined,id='')=>`<span ${id?`data-testid="${id}"`:''} data-value="${v??''}" title="${v??'unavailable'}">${number(v)}</span>`;
export const learningStations=[{stage:'objective',x:3270,title:'TARGETS → LOSS → MEAN'},{stage:'gradient',x:2440,title:'CONTRIBUTIONS → GRADIENT'},{stage:'adam',x:1560,title:'ADAM · PERSISTENT STATE'},{stage:'checkpoint',x:670,title:'CHECKPOINT → FRESH FORWARD'}] as const;
export function learningScene(m:LearningModel|undefined,stage:LearningStage|undefined,pin:ParameterPin){
 const owner=stationFor(pin.name);
 return `<g class="learning-world"><text class="training-label" x="550" y="1170">ALL-POSITION OBJECTIVE · SELECTED PARAMETER SLICE · ${esc(parameterLabel(pin))}</text><path class="learning-link" d="M4100 650 V1230 H3720 M3270 1400 H2890 M2440 1400 H2010 M1560 1400 H1120 M670 1400 C${owner.x+70} 1400 ${owner.x+70} 1200 ${owner.x+70} 1085"/><path class="learning-link" d="M${owner.x+70} 1090 C${owner.x+70} 1205 2660 1190 2660 1260"/>${learningStations.map(s=>`<g role="button" tabindex="0" data-learning-stage="${s.stage}" aria-label="${s.title}"><rect x="${s.x}" y="1260" width="450" height="225" rx="5"/><text x="${s.x+18}" y="1305">${s.title}</text><text class="learning-value" x="${s.x+18}" y="1360">${!m?.available?'No completed transition':s.stage==='objective'?`mean ${number(m.objective.mean)}`:s.stage==='gradient'?`g = ${number(m.backward.gradient)}`:s.stage==='adam'?`θ ${number(m.adam.update?.before)} → ${number(m.adam.update?.after)}`:`step ${m.start.state.optimizer.step} → ${m.end.state.optimizer.step}`}</text><text class="learning-note" x="${s.x+18}" y="1410">${s.stage==='gradient'?'Summary collapses intermediate graph':s.stage==='objective'?'All positions, independent of selected query':esc(parameterLabel(pin))}</text>${stage===s.stage?reticle(s.x,1260,450,225):''}</g>`).join('')}<text class="learning-note" x="650" y="1550">Connections summarize a completed update; not arrival chronology, measured trajectory, or one-weight causal attribution.</text></g>`;
}
function comparison(m:Extract<LearningModel,{available:true}>,a:Address){
 const b=m.comparison.before.values(a),e=m.comparison.after.values(a),max=Math.max(0,...[...(b??[]),...(e??[])].map(Math.abs));
 const deltaMax=b&&e?Math.max(0,...b.map((v,i)=>Math.abs(e[i]-v))):0;
 const bar=(v:number,cls:string)=>`<span class="${cls}" style="left:${v<0?50+(max?50*v/max:0):50}%;width:${max?50*Math.abs(v)/max:0}%"></span>`;
 return `<h3>Before / after · ${esc(a.kind)} · position ${a.token}</h3><p>Matched inputs and targets. Original component axes; shared symmetric domain ±${number(max)} for both endpoints. No independently fitted Q/K or mixture planes are overlaid.</p><div data-testid="comparison-pairs">${b&&e&&b.length===e.length?b.map((v,i)=>`<div class="endpoint-row" data-before="${v}" data-after="${e[i]}" data-domain="${max}"><span>[${i}]</span><div class="endpoint-track">${bar(v,'endpoint-before')}${bar(e[i],'endpoint-after')}</div><span>${number(v)} → ${number(e[i])}</span><span>Δ ${number(e[i]-v)}</span></div>`).join(''):'Unavailable endpoint components.'}</div><p>Before = neutral / upper; after = cyan / lower. Numeric differences have no amplified glyph; maximum absolute difference ${number(deltaMax)}.</p><p>Selected parameter ${esc(parameterLabel(m.pin))}: ${val(m.adam.update?.before)} → ${val(m.adam.update?.after)}. All model parameters participated; this cell alone does not explain output changes.</p><h3>Matched all-position loss</h3><p>${m.beforeObjective.origin} before ${val(m.beforeObjective.mean,'comparison-before-loss')} → ${m.afterObjective.origin} after ${val(m.afterObjective.mean,'comparison-after-loss')}</p><p>After loss uses fresh after-run probabilities and matching targets. No clamp and no assumption that loss decreases.</p><p>Before <code>${esc(m.before.manifest.runId)}</code><br>After <code>${esc(m.after.manifest.runId)}</code><br>Snapshots <code>${esc(m.start.id)}</code> → <code>${esc(m.end.id)}</code></p>`;
}
export function learningInspector(m:LearningModel|undefined,stage:LearningStage,pin:ParameterPin,a:Address,scalar:string,expanded:boolean){
 const header=`<div class="lens-heading"><div><small>COMPLETED LEARNING · ${stage.toUpperCase()}</small><h2>${esc(parameterLabel(pin))}</h2></div><button id="close-spatial-lens" aria-label="Close arithmetic lens">×</button></div><div class="lens-context"><button id="learning-owner">Forward owner</button><button id="lens-home">Home</button><button id="lens-back">Back</button></div>`;
 if(!m?.available)return `${header}<div class="lens-scroll"><p>${esc(m?.reason??'No completed transition. Select a parameter and Learn one real update.')}</p></div>`;
 const u=m.adam.update!,back=m.backward;
 let body='';
 if(stage==='objective')body=`<h3>All ${m.objective.rows.length} positions → mean objective</h3><p>The selected query ${a.token} does not narrow the training objective.</p><table data-testid="training-objective"><thead><tr><th>Position / input ID</th><th>Target ID</th><th>Observed P(target)</th><th>Observed −log P</th></tr></thead><tbody>${m.objective.rows.map(r=>`<tr><th>${r.position} / ${esc(r.inputLabel)} (${r.input})</th><td>${esc(r.targetLabel)} (${r.target})</td><td>${val(r.probability)}</td><td>${val(r.loss)} <button data-learning-loss="${r.position}">Scalar</button></td></tr>`).join('')}</tbody></table><p>Σ position losses / ${m.objective.rows.length} ≈ ${val(m.objective.mean,'training-mean')} OBSERVED</p><button id="learning-mean-scalar">Inspect mean scalar</button><button data-learning-stage="gradient">Follow selected parameter contributions →</button>`;
 if(stage==='gradient')body=`<h3>Actual incoming operand occurrences → sum</h3><p>${back.graphOrigin} · ${back.graphVerification} · source <code>${esc(m.training.manifest.runId)}</code></p><p>Recorded gradient ${val(back.gradient,'learning-gradient')} · captured graph gradient ${val(back.graphGradient)}</p><button id="learning-inspect-gradient">Inspect / verify parameter contributions</button>${back.fanInAvailable?`<p data-testid="contribution-accounting">${back.contributions.length} occurrences · ${back.visible.length} visible · ${back.hiddenCount} hidden</p><table data-testid="learning-contributions"><thead><tr><th>Occurrence / child</th><th>Child adjoint</th><th>Local derivative</th><th>Contribution</th></tr></thead><tbody>${back.visible.map(edge=>`<tr><td><button data-learning-edge="${edge.child}">edge ${edge.id} · operand ${edge.inputIndex}</button></td><td>${val(edge.childAdjoint)}</td><td>${val(edge.localDerivative)}</td><td>${val(edge.contribution)}</td></tr>`).join('')}</tbody></table><p>Visible subtotal ${val(back.visible.reduce((s,e)=>s+e.contribution!,0))} + hidden subtotal ${val(back.hiddenSubtotal??0,'hidden-subtotal')} ≈ total ${val(back.sum,'contribution-total')}</p><button id="learning-expand">${expanded?'Show bounded list':'Expand all occurrences'}</button>`:'<p>No accepted decomposition yet. A zero gradient is not missing evidence.</p>'}<p>Each repeated operand edge is counted once. Expanding a child explains it; its ancestors are not added again. These final contributions have no measured arrival order or token attribution.</p><button data-learning-stage="adam">Gradient + old moments → Adam</button>`;
 if(stage==='adam')body=`<h3>Actual Adam · update ${m.end.state.optimizer.step}</h3><div class="adam-chain"><section><b>Persistent inputs</b><p>g ${val(u.gradient,'adam-gradient')}<br>m before ${val(u.mBefore,'adam-m-before')}<br>v before ${val(u.vBefore,'adam-v-before')}</p></section><span>↓</span><section><b>Moment calculation</b><p>m′ = β₁m + (1−β₁)g ≈ ${val(u.mAfter,'adam-m-after')}<br>v′ = β₂v + (1−β₂)g² ≈ ${val(u.vAfter,'adam-v-after')}</p><p>β₁ ${val(m.adam.beta1)} · β₂ ${val(m.adam.beta2)}</p></section><span>↓</span><section><b>Corrections → update</b><p>1−β₁ᵗ ${val(u.biasCorrection1)} · 1−β₂ᵗ ${val(u.biasCorrection2)}<br>m̂ ${val(u.mHat)} · v̂ ${val(u.vHat)}<br>effective lr ${val(m.adam.effectiveLearningRate)} · ε ${val(m.adam.epsilon)}</p><p>q = lr · m̂ / (√v̂ + ε) ≈ ${val(m.adam.q)}<br>θ′ = θ − q</p></section><span>↓</span><section><b>Stored endpoint</b><p>${val(u.before,'adam-before')} → ${val(u.after,'adam-after')}<br>Representable stored delta θ′−θ = ${val(u.delta,'adam-delta')}</p></section></div><p>Recorded fields and starting optimizer configuration, not inferred betas. A signed formula quantity q is distinct from representable stored delta.</p><button data-learning-stage="checkpoint">Follow resulting checkpoint / fresh forward →</button>`;
 if(stage==='checkpoint')body=`<h3>Persistent checkpoint ${m.start.state.optimizer.step} → ${m.end.state.optimizer.step}</h3><p>${esc(parameterLabel(pin))}: ${val(u.before)} → ${val(u.after)}</p><p>Starting <code>${esc(m.start.id)}</code><br>Resulting <code>${esc(m.end.id)}</code></p><button data-learning-phase="after">View fresh after-run throughout the model</button><button data-learning-stage="compare">Compare matched endpoints</button><p>The whole parameter set was updated. An endpoint connection is not an interpolated trajectory.</p>`;
 if(stage==='compare')body=comparison(m,a);
 return `${header}<div class="lens-scroll" data-scroll-region="spatial-lens">${body}<section class="spatial-scalar" id="microscope">${scalar}</section><footer data-testid="learning-source"><p>Experiment <code>${esc(m.experiment.id)}</code><br>Training <code>${esc(m.training.manifest.runId)}</code><br>Starting snapshot <code>${esc(m.start.id)}</code><br>Resulting snapshot <code>${esc(m.end.id)}</code></p></footer></div>`;
}
