import type { TrainingProgress } from '../worker/training-execution.js';
import { escapeHtml as esc } from '../views/evidence.js';
import { stationFor } from './scene.js';
import type { ParameterPin } from './learning.js';
const n = (v: number) => Number(v.toPrecision(8)).toString();
export function liveLearningScene(t: TrainingProgress, pin: ParameterPin) {
  const event = t.contributions.at(-1), u = t.proposal;
  const owner = stationFor(pin.name);
  const x = t.phase === 'loss' ? 3270 : t.phase.includes('backward') ? 2440 : 1560;
  const lines = t.phase === 'loss' ? [...t.losses.slice(0,3).map((l,i)=>`p${i} target ${l.target} · loss ${l.value === undefined ? 'pending' : n(l.value)}`),`mean ${t.mean === undefined ? 'pending' : n(t.mean)} · all ${t.losses.length} rows in lens`] : u ? [`g ${n(u.gradient)} + old m ${n(u.mBefore)} / v ${n(u.vBefore)}`, `→ proposed m ${n(u.mAfter)} / v ${n(u.vAfter)}`, `→ m̂ ${n(u.mHat)} / v̂ ${n(u.vHat)}`, `θ ${n(u.before)} + Δ ${n(u.delta)} → ${n(u.after)}`]
    : event ? [`${n(event.childAdjoint)} × ${n(event.localDerivative)} = ${n(event.contribution)}`, `${n(event.before)} + ${n(event.contribution)} → ${n(event.after)}`, `${t.final?'FINAL':'PARTIAL'} g ${n(t.gradient)}`] : [`${t.final?'FINAL':'PARTIAL'} g ${n(t.gradient)}`, 'Next contribution / proposal pending'];
  return `<g class="learning-world" data-testid="live-local-construction"><path class="learning-link" d="M${owner.x+70} 1085 V1190 H${x+100} V1260"/><text class="learning-note" x="${x}" y="1225">Owner ${esc(pin.name)} · scalar slice, not full derivative graph</text><rect x="${x}" y="1260" width="700" height="260" rx="5"/><text x="${x+18}" y="1295">${esc(pin.name)}[${pin.row},${pin.column}] · ${t.phase==='loss'?'TARGET LOSSES → MEAN':u?'PROPOSED ADAM':'ACTUAL ACCUMULATION'}</text>${lines.map((line,i)=>`<text class="learning-value" x="${x+18}" y="${1335+i*40}">${esc(line)}</text>`).join('')}</g>`;
}
export function liveLearningInspector(t: TrainingProgress, pin: ParameterPin, scalar: string) {
  const e = t.contributions.at(-1), u = t.proposal;
  // Fixed declared signed domain; clip only marks, never numbers.
  const mark = (v: number) => `<span class="live-signed-track"><i style="left:${v < 0 ? 50-50*Math.min(1,Math.abs(v)) : 50}%;width:${50*Math.min(1,Math.abs(v))}%;background:${v<0?'#DC7C7C':'#58B98C'}"></i></span>`;
  const objective = `<section><h3>All-position target losses → mean</h3>${t.losses.map((l,i)=>`<p>p${i} target ${l.target}: ${l.value===undefined?'pending':n(l.value)}</p>`).join('')}<p>Ordered mean ${t.mean===undefined?'pending':n(t.mean)}</p></section>`;
  const contribution = `<section><h3>${t.final?'Final':'Partial'} gradient <span data-testid="live-gradient" data-value="${t.gradient}">${n(t.gradient)}</span></h3>${e?`<p>Occurrence ${e.ordinal} · operand ${e.operand} · child <button data-live-child="${e.child}" data-live-source="${esc(t.gradientSourceRunId)}">scalar ${e.child}</button></p><p data-testid="live-contribution">${n(e.childAdjoint)} × ${n(e.localDerivative)} = ${n(e.contribution)}</p><div class="live-arithmetic-row">Contribution ${mark(e.contribution)} ${n(e.contribution)}</div><div class="live-arithmetic-row">Accumulator ${mark(e.before)} ${n(e.before)}</div><div class="live-arithmetic-row">After addition ${mark(e.after)} ${n(e.after)}</div><p class="live-scale">Signed marks: fixed −1…+1, clipped at endpoints; exact numbers shown. Count is separate from magnitude.</p>`:t.final?'<p>Traversal complete. Earlier live occurrences were not retained for this pin; the final gradient is available. No rewind.</p>':'<p>Contribution pending. Inspection grants no work.</p>'}</section>`;
  const optimizer = `<section><h3>Optimizer · ${u?'proposed, not persistent':'pending'}</h3>${u?`<div class="adam-chain" data-testid="live-proposal"><section>Old θ ${n(u.before)} · m ${n(u.mBefore)} · v ${n(u.vBefore)}<br>Final g ${n(u.gradient)}</section><span>↓</span><section>m′ = β₁m + (1−β₁)g · β₁ ${n(t.optimizer.beta1)}<br>v′ = β₂v + (1−β₂)g² · β₂ ${n(t.optimizer.beta2)}<br>Proposed m′ ${n(u.mAfter)} · v′ ${n(u.vAfter)}<br>Corrections ${n(u.biasCorrection1)} / ${n(u.biasCorrection2)}<br>m̂ ${n(u.mHat)} · v̂ ${n(u.vHat)}</section><span>↓</span><section>θ′ = θ − lr m̂ / (√v̂ + ε)<br>lr ${n(t.optimizer.effectiveLearningRate)} · ε ${n(t.optimizer.epsilon)}<br>Stored Δ ${n(u.delta)} → candidate θ′ ${n(u.after)}</section></div>`:`<p>Accepted θ ${n(t.old.parameter)} · m ${n(t.old.m)} · v ${n(t.old.v)}. Proposals have not executed.</p>`}</section>`;
  const proposalPhase=['optimizer proposal','candidate application','ready'].includes(t.phase);
  return `<div class="lens-heading"><div><small>LIVE · ${esc(t.phase)} · accepted step ${t.acceptedStep}</small><h2>${esc(pin.name)}[${pin.row},${pin.column}]</h2></div><button id="close-spatial-lens" aria-label="Close arithmetic lens">×</button></div><div class="lens-context"><button id="learning-owner">Forward owner</button><button id="lens-home">Home</button><button id="lens-back">Back</button></div><div class="lens-scroll live-learning" data-scroll-region="spatial-lens" data-testid="live-learning-arithmetic"><p class="live-scope">All ${t.losses.length} positions · mean ${t.mean===undefined?'pending':n(t.mean)} · candidate step ${t.acceptedStep+1} provisional</p>${t.phase==='loss'?objective:proposalPhase?optimizer+contribution:contribution+optimizer}<details><summary>Recent processed occurrences (${t.contributions.length}, latest 8 retained)</summary>${t.contributions.map(c=>`<p>#${c.ordinal} / operand ${c.operand}: ${n(c.before)} + ${n(c.contribution)} = ${n(c.after)}</p>`).join('')}</details><p>Source <code>${esc(t.sourceRunId)}</code><br>${t.candidateId?`Provisional checkpoint <code>${esc(t.candidateId)}</code>`:'Candidate checkpoint pending'}</p><section id="microscope">${scalar}</section></div>`;
}
