import {test,expect} from '../support/browser-evidence.js';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {validateScratchPath} from '../support/slice-output.js';

const pythiaEndpoint=process.env.PYTHIA_NATIVE_ENDPOINT??process.env.SLICE_NATIVE_ENDPOINT;
const witnessEndpoint=process.env.WITNESS_NATIVE_ENDPOINT;
const recordings=process.env.WITNESS_RECORDING_DIR;

async function setCoordinate(page:import('@playwright/test').Page,role:string,value:number){const control=page.locator(`[data-pythia-coordinate="${role}"]`);if(await control.evaluate(el=>el instanceof HTMLSelectElement))await control.selectOption(String(value));else{await control.fill(String(value));await control.dispatchEvent('change');}}

test('M2-D live native Pythia inhabits the shared world with truthful selected-layer coverage',async({page,evidenceDir:dir})=>{
  test.skip(process.env.SLICE_PHASE==='offline'||!pythiaEndpoint,'live pinned Pythia endpoint required');const errors:string[]=[];let step='start';page.on('pageerror',error=>errors.push(`${step}: ${error.message}`));
  await page.setViewportSize({width:1920,height:1080});await page.goto('/?presentation=spatial');step='execute native';await page.locator('#open-shared-inspector').click();await page.locator('#shared-model').selectOption('pythia-native-v1');await page.locator('#native-endpoint').fill(pythiaEndpoint!);await page.locator('#native-prompt').fill('The cat sat');
  const responsePromise=page.waitForResponse(response=>response.url()===pythiaEndpoint&&response.request().method()==='POST');await page.locator('#shared-execute').click();const response=await responsePromise;expect(response.status()).toBe(200);const native=await response.json();await expect(page.getByTestId('shared-status')).toContainText('receipt validated');
  await page.locator('#shared-save').click();const saved=await page.evaluate(()=>localStorage.getItem('model-lab-evidence-v1')!);const handoff=await validateScratchPath(process.cwd(),process.env.M2D_HANDOFF_DIR!);await mkdir(`${handoff}/live`,{recursive:false});await writeFile(`${handoff}/live/pythia-saved.json`,saved);await writeFile(`${handoff}/live/pythia-response.json`,JSON.stringify(native));
  step='open pythia world';await page.locator('#shared-world').click();await expect(page.locator('.pythia-overview-node[data-pythia-block]')).toHaveCount(6);await expect(page.getByTestId('pythia-coverage')).toContainText('block 1: observed detail');await expect(page.getByTestId('pythia-coverage')).toContainText('block 5: structure only / uncaptured');await page.screenshot({path:`${dir}/m2-d-pythia-overview-1920.png`});
  step='select blocks';await page.locator('[data-pythia-block="0"]').click();await expect(page.locator('.pythia-world')).toContainText('BLOCK 0 · STRUCTURALLY KNOWN, NUMERICALLY UNCAPTURED');await page.locator('[data-pythia-block="1"]').click();await expect(page.locator('[data-origin="observed"]')).toHaveCount(11);await expect(page.locator('.pythia-world')).toContainText('PARALLEL RESIDUAL');await expect(page.locator('.pythia-world')).toContainText('LayerNorm · same residual input');await expect(page.locator('.pythia-world')).toContainText('affine with bias → 512 → GELU');await page.screenshot({path:`${dir}/m2-d-pythia-block1-parallel-1920.png`});
  const weights=native.record.points.find((point:any)=>point.id==='attention.weights'),tokens=native.record.input.tokenIds.length,query=tokens-1,key=Math.max(0,query-1);
  step='select attention head 0';await page.locator('#pythia-operation').selectOption('attention.weights');await setCoordinate(page,'query_head',0);await setCoordinate(page,'query_position',query);await setCoordinate(page,'key_position',key);const index=(head:number)=>head*tokens*tokens+query*tokens+key,head0=weights.values[index(0)];await expect(page.getByTestId('pythia-attention-probability')).toContainText(`= ${head0}`);await page.screenshot({path:`${dir}/m2-d-pythia-attention-head0-1920.png`});
  step='select attention head 2';await setCoordinate(page,'query_head',2);const head2=weights.values[index(2)];await expect(page.getByTestId('pythia-attention-probability')).toContainText(`= ${head2}`);await page.screenshot({path:`${dir}/m2-d-pythia-attention-head2-1920.png`});
  step='navigate qkv and refuse';await page.locator('#pythia-related-qkv').click();await expect(page.getByTestId('pythia-prerope')).toContainText('PRE-RoPE');await expect(page.getByTestId('pythia-prerope')).toContainText('not the rotated operands');await page.locator('#pythia-detail').click();await expect(page.getByTestId('pythia-refusal')).toContainText('post-RoPE Q/K and attention scores were not captured');await page.screenshot({path:`${dir}/m2-d-pythia-prerope-refusal-1920.png`});
  step='select mlp and residual';await page.locator('#pythia-operation').selectOption('mlp.output');await expect(page.locator('.pythia-lens')).toContainText('Preactivations and hidden activations were not captured');await page.locator('#pythia-operation').selectOption('residual.output');await expect(page.getByTestId('pythia-parallel-proof')).toContainText('(attention.output + mlp.output) + residual.input');
  step='select logits and source';await page.locator('#pythia-operation').selectOption('logits');await setCoordinate(page,'output_index',50303);await expect(page.getByTestId('pythia-topk').locator('tbody tr')).toHaveCount(5);await expect(page.getByTestId('pythia-omitted-mass')).toBeVisible();await expect(page.getByTestId('pythia-selected-output')).toContainText('Exact output index 50303');await expect(page.getByTestId('pythia-selected-output')).toContainText('No tokenizer label exists');await page.getByTestId('pythia-source').locator('summary').click();await expect(page.getByTestId('pythia-source')).toContainText('class GPTNeoX');await page.screenshot({path:`${dir}/m2-d-pythia-logits-50303-1920.png`});

  step='return canonical';await page.locator('#return-canonical-world').click();await expect(page.locator('.pythia-shell')).toHaveCount(0);await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');await expect(page.locator('#spatial-layer')).toHaveValue('0');
  if(witnessEndpoint&&recordings){
    step='switch to mlp';
    await page.locator('#open-shared-inspector').click();await page.locator('#shared-model').selectOption('mlp-native-v1');await page.locator('#native-endpoint').fill(witnessEndpoint);const mlpResponse=page.waitForResponse(r=>r.url()===witnessEndpoint&&r.request().method()==='POST');await page.locator('#shared-execute').click();await mlpResponse;await expect(page.getByTestId('shared-status')).toContainText('receipt validated');await page.locator('#shared-world').click();await expect(page.locator('.mlp-shell')).toBeVisible();await expect(page.locator('[data-pythia-coordinate]')).toHaveCount(0);
    step='switch to fallback';await page.locator('#return-canonical-world').click();await page.locator('#open-shared-inspector').click();await page.locator('#shared-import').setInputFiles(`${recordings}/shape.json`);await expect(page.getByTestId('shared-status')).toContainText('Saved replay loaded');await page.locator('#shared-world').click();await expect(page.locator('.fallback-shell')).toBeVisible();await expect(page.locator('[data-pythia-coordinate],[data-mlp-coordinate]')).toHaveCount(0);
    step='switch back to pythia';await page.locator('#return-canonical-world').click();await page.locator('#open-shared-inspector').click();await page.evaluate(value=>localStorage.setItem('model-lab-evidence-v1',value),saved);await page.locator('#shared-load').click();await page.locator('#shared-world').click();await expect(page.locator('.pythia-shell')).toBeVisible();await expect(page.locator('[data-pythia-coordinate="input_position"]')).toHaveValue('0');await expect(page.locator('[data-fallback-coordinate],[data-mlp-coordinate]')).toHaveCount(0);
    await page.setViewportSize({width:1280,height:720});await page.emulateMedia({reducedMotion:'reduce'});await page.screenshot({path:`${dir}/m2-d-switch-chain-reduced-1280.png`});
  }
  expect(errors).toEqual([]);await writeFile(`${dir}/m2-d-live.json`,JSON.stringify({run:native.record.id,runtime:native.record.runtime,tokens:native.record.input.tokenIds,attention:{query,key,heads:[{head:0,value:head0},{head:2,value:head2}]},outputIndex50303:native.record.points.find((point:any)=>point.id==='logits').values[50303],switchChain:Boolean(witnessEndpoint&&recordings),errors},null,2));
});

test('M2-D saved Pythia world replays after verified bridge shutdown with zero native requests',async({page,evidenceDir:dir})=>{
  test.skip(process.env.SLICE_PHASE!=='offline');const handoff=await validateScratchPath(process.cwd(),process.env.M2D_HANDOFF_DIR!),saved=await readFile(`${handoff}/live/pythia-saved.json`,'utf8'),native=JSON.parse(await readFile(`${handoff}/live/pythia-response.json`,'utf8'));let requests=0;
  page.on('request',request=>{if(request.url()===pythiaEndpoint)requests++;});await page.setViewportSize({width:1280,height:720});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/?presentation=spatial');await page.locator('#open-shared-inspector').click();await page.evaluate(value=>localStorage.setItem('model-lab-evidence-v1',value),saved);await page.locator('#shared-load').click();await expect(page.getByTestId('shared-provenance')).toContainText('SAVED REPLAY');await page.locator('#shared-world').click();await expect(page.locator('.spatial-badge')).toContainText('SAVED REPLAY · NO EXECUTION');
  const tokens=native.record.input.tokenIds.length,query=tokens-1,key=0,weights=native.record.points.find((point:any)=>point.id==='attention.weights');await page.locator('#pythia-operation').selectOption('attention.weights');await setCoordinate(page,'query_head',1);await setCoordinate(page,'query_position',query);await setCoordinate(page,'key_position',key);await expect(page.getByTestId('pythia-attention-probability')).toContainText(String(weights.values[1*tokens*tokens+query*tokens+key]));await page.locator('#pythia-related-qkv').click();await page.locator('#pythia-detail').click();await expect(page.getByTestId('pythia-refusal')).toContainText('Executor disconnected');
  await page.locator('#pythia-operation').selectOption('logits');await setCoordinate(page,'output_index',50303);await expect(page.getByTestId('pythia-selected-output')).toContainText(String(native.record.points.find((point:any)=>point.id==='logits').values[50303]));await page.screenshot({path:`${dir}/m2-d-pythia-replay-reduced-1280.png`});
  await page.locator('#return-canonical-world').click();await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');expect(requests).toBe(0);await writeFile(`${dir}/m2-d-offline.json`,JSON.stringify({nativeRequests:requests,replayAttention:true,replayLogit50303:true,unsupportedDetail:'disconnected',canonicalPredictWithoutPython:true,reducedMotion:true},null,2));
});
