import {test,expect} from '../support/browser-evidence.js';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {validateScratchPath} from '../support/slice-output.js';

const endpoint=process.env.PYTHIA_NATIVE_ENDPOINT??process.env.SLICE_NATIVE_ENDPOINT;
async function coordinate(page:import('@playwright/test').Page,role:string,value:number){const control=page.locator(`[data-pythia-coordinate="${role}"]`);if(await control.evaluate(element=>element instanceof HTMLSelectElement))await control.selectOption(String(value));else{await control.fill(String(value));await control.dispatchEvent('change');}}

test('M4-A live Predict and bounded uncached Generate retain separate native occurrences',async({page,evidenceDir:directory})=>{
  test.skip(process.env.SLICE_PHASE==='offline'||!endpoint,'live pinned Pythia bridge required');const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));
  await page.setViewportSize({width:1920,height:1080});await page.goto('/?presentation=spatial');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await page.locator('#open-shared-inspector').click();await page.locator('#shared-model').selectOption('pythia-native-v1');await page.locator('#native-endpoint').fill(endpoint!);await page.locator('#native-prompt').fill('The cat sat');
  let response=page.waitForResponse(value=>value.url()===endpoint&&value.request().method()==='POST');await page.locator('#shared-execute').click();let native=await (await response).json();expect(native.record.request.action).toBe('predict');expect(native.record.points.find((point:any)=>point.id==='logits').shape).toEqual([50304]);await expect(page.getByTestId('shared-status')).toContainText('receipt validated');
  await page.locator('#shared-action').selectOption('generate');response=page.waitForResponse(value=>value.url()===endpoint&&value.request().method()==='POST');await page.locator('#shared-execute').click();native=await (await response).json();await expect(page.getByTestId('shared-status')).toContainText('receipt validated');
  const generation=native.record.generation;expect(generation.generated.tokenIds).toEqual([327,253]);expect(generation.invocations.map((item:any)=>item.identity)).toEqual(['prefill:0','generation:1','generation:2']);expect(generation.cancellationEpoch).not.toBe(generation.invocations[1].generatedStep);
  await page.locator('#shared-save').click();const saved=await page.evaluate(()=>localStorage.getItem('model-lab-evidence-v1')!);const handoff=await validateScratchPath(process.cwd(),process.env.M4A_HANDOFF_DIR!);await mkdir(`${handoff}/live`,{recursive:false});await writeFile(`${handoff}/live/generation-saved.json`,saved);await writeFile(`${handoff}/live/generation-response.json`,JSON.stringify(native));
  await page.locator('#shared-world').click();await expect(page.getByTestId('pythia-generation')).toBeVisible();await expect(page.getByTestId('pythia-effective-prefix')).toContainText('Prompt processing');await expect(page.getByTestId('pythia-effective-prefix')).toContainText('[510, 5798, 2206]');await expect(page.getByTestId('pythia-cache-policy')).toContainText('uncached · full prefix reexecuted');
  await page.locator('#pythia-invocation').selectOption('generation:1');await expect(page.getByTestId('pythia-effective-prefix')).toContainText('generated step 1');await expect(page.getByTestId('pythia-effective-prefix')).toContainText('Argmax choice: 327');await page.locator('#pythia-operation').selectOption('generation:1/attention.weights');await coordinate(page,'query_head',0);await coordinate(page,'query_position',2);await coordinate(page,'key_position',1);const first=await page.getByTestId('pythia-attention-probability').textContent();await coordinate(page,'query_head',2);const second=await page.getByTestId('pythia-attention-probability').textContent();expect(first).not.toBe(second);
  await page.locator('#pythia-invocation').selectOption('generation:2');await expect(page.getByTestId('pythia-effective-prefix')).toContainText('[510, 5798, 2206, 327]');await page.locator('#pythia-operation').selectOption('generation:2/logits');await coordinate(page,'output_index',50303);await expect(page.getByTestId('pythia-topk').locator('tbody tr')).toHaveCount(5);await expect(page.getByTestId('pythia-omitted-mass')).toBeVisible();await expect(page.getByTestId('pythia-selected-output')).toContainText('Exact output index 50303');await page.screenshot({path:`${directory}/m4-a-generation-step2-1920.png`});
  await page.locator('#pythia-operation').selectOption('generation:2/choice');await expect(page.locator('.pythia-lens')).toContainText('Derived generation-policy decision');await expect(page.getByTestId('pythia-selected-value')).toContainText('253');await page.screenshot({path:`${directory}/m4-a-choice-evidence-1920.png`});
  await page.locator('#return-canonical-world').click();await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');expect(errors).toEqual([]);await writeFile(`${directory}/m4-a-live.json`,JSON.stringify({promptIds:native.record.run.input.tokenIds,generatedIds:generation.generated.tokenIds,invocations:generation.invocations.map((item:any)=>({identity:item.identity,step:item.generatedStep,prefix:item.effectivePrefixIds})),cache:generation.cache,stop:generation.termination,twoHeads:first!==second,canonicalPredictAfterGeneration:true,errors},null,2));
});

test('M4-A retained generation replays with zero native requests after bridge shutdown',async({page,evidenceDir:directory})=>{
  test.skip(process.env.SLICE_PHASE!=='offline','offline replay phase required');const handoff=await validateScratchPath(process.cwd(),process.env.M4A_HANDOFF_DIR!),saved=await readFile(`${handoff}/live/generation-saved.json`,'utf8'),native=JSON.parse(await readFile(`${handoff}/live/generation-response.json`,'utf8'));let requests=0;page.on('request',request=>{if(request.url()===endpoint)requests++;});
  await page.setViewportSize({width:1280,height:720});await page.emulateMedia({reducedMotion:'reduce'});await page.goto('/?presentation=spatial');await page.locator('#open-shared-inspector').click();await page.evaluate(value=>localStorage.setItem('model-lab-evidence-v1',value),saved);await page.locator('#shared-load').click();await expect(page.getByTestId('shared-provenance')).toContainText('SAVED REPLAY');await page.locator('#shared-world').click();await expect(page.locator('.spatial-badge')).toContainText('SAVED REPLAY · NO EXECUTION');
  await page.locator('#pythia-invocation').selectOption('generation:2');await page.locator('#pythia-operation').selectOption('generation:2/attention.qkv');await coordinate(page,'input_position',3);await coordinate(page,'query_head',1);await coordinate(page,'qkv_member',0);await coordinate(page,'head_feature',7);await expect(page.getByTestId('pythia-prerope')).toContainText('PRE-RoPE');await page.locator('#pythia-detail').click();await expect(page.getByTestId('pythia-refusal')).toContainText('Executor disconnected');
  await page.locator('#pythia-operation').selectOption('generation:2/logits');await coordinate(page,'output_index',50303);const logit=native.record.run.points.find((point:any)=>point.id==='generation:2/logits').values[50303];await expect(page.getByTestId('pythia-selected-output')).toContainText(String(logit));await expect(page.getByTestId('pythia-cache-policy')).toContainText('cache unsupported/unqualified');await page.screenshot({path:`${directory}/m4-a-replay-reduced-1280.png`});
  await page.locator('#return-canonical-world').click();await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');expect(requests).toBe(0);await writeFile(`${directory}/m4-a-offline.json`,JSON.stringify({nativeRequests:requests,replayedInvocations:3,exactLogit50303:logit,uncapturedDetail:'refused-disconnected',cache:'unsupported',canonicalPredictAfterReplay:true,reducedMotion:true},null,2));
});
