import {test,expect} from '../support/browser-evidence.js';
import {readFile,writeFile} from 'node:fs/promises';

const recording=process.env.NATIVE_GENERATION_RECORDING;
async function coordinate(page:import('@playwright/test').Page,role:string,value:number){const control=page.locator(`[data-pythia-coordinate="${role}"]`);if(await control.evaluate(element=>element instanceof HTMLSelectElement))await control.selectOption(String(value));else{await control.fill(String(value));await control.dispatchEvent('change');}}

test('M4-B1 retained generation uses payload-backed bounded inspection with no executor',{tag:'@m4-b1'},async({page,evidenceDir:directory})=>{
  test.skip(!recording,'qualified M4-A generation recording required');const envelope=JSON.parse(await readFile(recording!,'utf8')),expected=envelope.record.run.points.find((point:any)=>point.id==='generation:2/logits').values[50303],sourceFile=envelope.record.run.points.find((point:any)=>point.id==='generation:1/residual.input').source.file;let nativeRequests=0;page.on('request',request=>{if(request.url().includes('/execute'))nativeRequests++;});
  await page.setViewportSize({width:1920,height:1080});await page.goto('/?presentation=spatial');await page.locator('#open-shared-inspector').click();await page.locator('#shared-import').setInputFiles(recording!);await expect(page.getByTestId('shared-status')).toContainText('Saved replay loaded');
  const logits=page.locator('[data-point]').filter({hasText:'lm_head / output'}).nth(2);await logits.click();await expect(page.getByTestId('shared-storage')).toContainText('payload-backed');await expect(page.getByTestId('shared-storage')).toContainText('201216 bytes');await page.locator('#shared-offset').fill('50303');await page.locator('#shared-offset').dispatchEvent('change');await expect(page.getByTestId('shared-values')).toContainText(String(expected));await expect(page.locator('#shared-save')).toBeDisabled();await expect(page.locator('#shared-export')).toBeDisabled();await page.screenshot({path:`${directory}/m4-b1-payload-inspector-1920.png`});
  await page.locator('#shared-world').click();await expect(page.locator('.spatial-badge')).toContainText('SAVED REPLAY · NO EXECUTION');await page.locator('#pythia-invocation').selectOption('generation:2');await page.locator('#pythia-operation').selectOption('generation:2/logits');await coordinate(page,'output_index',50303);await expect(page.getByTestId('pythia-topk').locator('tbody tr')).toHaveCount(5);await expect(page.getByTestId('pythia-omitted-mass')).toBeVisible();await expect(page.getByTestId('pythia-selected-output')).toContainText(`observed logit ${expected}`);await page.screenshot({path:`${directory}/m4-b1-exact-logit-1920.png`});
  await page.locator('#pythia-operation').selectOption('generation:2/attention.qkv');await coordinate(page,'input_position',3);await coordinate(page,'query_head',1);await coordinate(page,'qkv_member',0);await coordinate(page,'head_feature',7);await expect(page.getByTestId('pythia-prerope')).toContainText('PRE-RoPE');await page.locator('#pythia-invocation').selectOption('generation:1');await expect(page.getByTestId('pythia-effective-prefix')).toContainText('generation:1');await expect(page.getByTestId('pythia-cache-policy')).toContainText('cache unsupported/unqualified');await expect(page.getByTestId('pythia-source')).toContainText(sourceFile);
  expect(nativeRequests).toBe(0);await page.screenshot({path:`${directory}/m4-b1-payload-replay-1920.png`});await writeFile(`${directory}/m4-b1-browser.json`,JSON.stringify({run:envelope.record.run.id,invocations:3,logitsPayloadBytes:201216,outputIndex:50303,exactLogit:expected,nativeRequests,cache:'unsupported',source:sourceFile},null,2));
});
