import { test, expect } from '@playwright/test';

test('progressive disclosure follows live operands, preserves captured detail, and verifies historical detail offline', async ({ page }) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/*', route => route.request().url().startsWith('http://127.0.0.1:4173/') ? route.continue() : route.abort());
  await page.goto('/');
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await expect(page.locator('#head')).toBeHidden();
  await page.getByRole('button', { name: 'Explore', exact: true }).click();
  const original = await page.locator('#history-run').inputValue();
  await page.locator('[data-stage="embeddingSum"]').click();
  await page.getByTestId('vector-evidence').locator('[data-element="2"]').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('OBSERVED LIVE SCALAR');
  await expect(page.getByTestId('scalar-operation')).toContainText('add');
  await page.getByTestId('microscope-evidence').locator('.source summary').last().click();
  await expect(page.getByTestId('microscope-evidence').locator('.source')).toContainText('Value.add');
  await expect(page.getByTestId('microscope-evidence').locator('.source')).toContainText('SHA-256');
  await page.getByTestId('microscope-evidence').locator('.operand-list').first().locator('button').first().click();
  await expect(page.getByTestId('scalar-operation')).toContainText('wte');
  await expect(page.getByTestId('microscope-evidence')).toContainText('Terminal parameter');
  await page.locator('.breadcrumbs button').first().click();
  await expect(page.getByTestId('scalar-operation')).toContainText('add');
  await page.locator('#predict').click();
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await expect(page.getByTestId('scalar-equation')).toHaveCount(0);
  await page.locator('#history-run').selectOption(original);
  await page.locator('[data-stage="embeddingSum"]').click();
  await page.getByTestId('vector-evidence').locator('[data-element="2"]').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('OBSERVED LIVE SCALAR');
  await page.getByTestId('vector-evidence').locator('[data-element="3"]').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('VERIFIED RECOMPUTATION');
  await expect(page.getByTestId('verification')).toContainText('max absolute error');
  // Reconstructed graph addresses support recursive navigation under this runtime revision.
  const liveStep = await page.getByTestId('training-step').textContent();
  await page.getByTestId('microscope-evidence').locator('.operand-list').first().locator('button').first().click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('VERIFIED RECOMPUTATION');
  await expect(page.getByTestId('scalar-operation')).toContainText('wte');
  await expect(page.getByTestId('verification')).toContainText('max absolute error');
  await expect(page.getByTestId('training-step')).toHaveText(liveStep!);
  // A new Predict invalidates an older in-flight inspection without losing the cache.
  await page.evaluate(() => {
    (document.querySelector('[data-testid="vector-evidence"] [data-element="4"]') as HTMLButtonElement).click();
    (document.querySelector('#predict') as HTMLButtonElement).click();
  });
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await expect(page.getByTestId('scalar-equation')).toHaveCount(0);
  expect(errors).toEqual([]);
});

test('actual training exposes loss, contributions, Adam equations, compatible history, and distinct reset intents', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await page.getByRole('button', { name: 'Explore', exact: true }).click();
  const initial = await page.locator('#history-run').inputValue();
  await page.locator('#train').click();
  await expect(page.getByTestId('training-step')).toHaveText('1');
  await page.locator('#parameter-select').selectOption('0');
  await page.getByTestId('adam-equations').locator('summary').click();
  await expect(page.getByTestId('adam-equations')).toContainText('β₁ = 0.85');
  await expect(page.getByTestId('adam-equations')).toContainText('mathematical update');
  await expect(page.getByTestId('adam-equations')).toContainText('actual representable delta');
  await page.locator('#inspect-gradient').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('OBSERVED LIVE SCALAR');
  await expect(page.getByTestId('gradient-edges').locator('tbody tr').first()).toBeVisible();
  const equations = await page.getByTestId('gradient-edges').locator('tbody tr').evaluateAll(rows => rows.map(row => Array.from(row.querySelectorAll('td[title]')).map(cell => Number(cell.getAttribute('title')))));
  for (const [adjoint, derivative, contribution] of equations) expect(adjoint * derivative).toBeCloseTo(contribution, 13);
  const training = await page.locator('#history-run option').evaluateAll(options => options.find(option => (option as HTMLOptionElement).value.endsWith(':training'))?.getAttribute('value'));
  await page.locator('#history-run').selectOption(training!);
  await page.locator('[data-stage="loss"]').click();
  await page.getByTestId('vector-evidence').locator('[data-element="0"]').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('OBSERVED LIVE SCALAR');
  await page.locator('#compare-run').selectOption(initial);
  await expect(page.getByTestId('run-comparison')).toContainText('Artifact absent from before run');
  const history = await page.getByTestId('history-count').textContent();
  const trainedSnapshot = await page.locator('#snapshot-select option').evaluateAll(options => options.find(option => option.textContent?.startsWith('step 1 '))?.getAttribute('value'));
  await page.locator('#reset').click();
  await expect(page.getByTestId('status')).toContainText('Model reset');
  await expect(page.getByTestId('training-step')).toHaveText('0');
  await expect(page.getByTestId('history-count')).toHaveText(history!);
  await page.locator('#snapshot-select').selectOption(trainedSnapshot!);
  await page.locator('#reset').click();
  await expect(page.getByTestId('training-step')).toHaveText('1');
  await expect(page.getByTestId('history-count')).toHaveText(history!);
  await page.locator('#clear-session').click();
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await expect(page.locator('button[data-mode="guided"]')).toHaveAttribute('aria-pressed', 'true');
  await page.getByRole('button', { name: 'Explore', exact: true }).click();
  await expect(page.getByTestId('history-count')).toContainText('1 runs · 1 snapshots · 0 learning experiments');
});

test('bounded training retains real checkpoints and complete capture displays statistics', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await page.getByRole('button', { name: 'Explore', exact: true }).click();
  await page.getByText('Bounded learning and complete capture', { exact: true }).click();
  await page.locator('#training-count').fill('3');
  await page.locator('#training-count').press('Tab');
  await page.locator('#train-many').click();
  await expect(page.getByTestId('status')).toContainText('3/3 requested updates');
  await expect(page.getByTestId('training-step')).toHaveText('3');
  await expect(page.getByTestId('training-summary')).toContainText('3 actual update summaries');
  const capturedRun = await page.locator('#history-run').inputValue();
  await page.locator('#whole-capture').click();
  await expect(page.getByTestId('whole-stats')).toContainText('scalar nodes');
  await expect(page.getByTestId('microscope-evidence').locator('button')).toHaveCount(1);
  await page.locator('#predict').click();
  await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await page.locator('#history-run').selectOption(capturedRun);
  await page.locator('[data-stage="embeddingSum"]').click();
  await page.getByTestId('vector-evidence').locator('[data-element="6"]').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('OBSERVED LIVE SCALAR');
  await page.getByTestId('microscope-evidence').locator('.operand-list').first().locator('button').first().click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('OBSERVED LIVE SCALAR');
  await expect(page.getByTestId('scalar-operation')).toContainText('wte');
});

test('head ablation compares fresh observed arms and inspects declared historical intervention', async ({ page }) => {
  await page.goto('/'); await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  await page.getByRole('button', { name: 'Explore', exact: true }).click();
  await page.getByText('Experiment · head ablation', { exact: true }).click();
  await page.locator('#ablate-head').click();
  await expect(page.getByTestId('status')).toContainText('Observed ablation complete');
  await expect(page.getByTestId('training-step')).toHaveText('0');
  await expect(page.getByTestId('run-comparison')).toContainText('Selected run minus comparison run');
  await page.locator('[data-stage="headOutput"]').click();
  await page.getByTestId('vector-evidence').locator('[data-element="0"]').click();
  await expect(page.getByTestId('inspection-provenance')).toHaveText('VERIFIED RECOMPUTATION');
  await expect(page.getByTestId('microscope-evidence')).toContainText('declared head ablation');
});
