import {test,expect,evidenceDirectory} from '../support/browser-evidence.js';
import {writeFile} from 'node:fs/promises';
for(const size of [{name:'desktop',width:1920,height:1080,reduce:false},{name:'compact',width:1280,height:720,reduce:true},{name:'mobile',width:390,height:844,reduce:true}])test(`release Lab direct recipes and continuity · ${size.name}`,async({page})=>{
 test.setTimeout(180_000);await page.setViewportSize(size);await page.emulateMedia({reducedMotion:size.reduce?'reduce':'no-preference'});
 await page.addInitScript(()=>{const w=window as any;w.labAudit={commands:[],results:[]};const post=Worker.prototype.postMessage,seen=new WeakSet();Worker.prototype.postMessage=function(m:any,...rest:any[]){w.labAudit.commands.push(m.command);if(!seen.has(this)){seen.add(this);this.addEventListener('message',e=>{if(e.data.status==='result')w.labAudit.results.push(e.data.result);},{once:false});}return Reflect.apply(post,this,[m,...rest]);};});
 const dir=await evidenceDirectory(test.info()),capture=(s:string)=>page.screenshot({path:`${dir}/${s}.png`}),commands=()=>page.evaluate(()=>[...(window as any).labAudit.commands]);
 await page.goto('/?experience=learn&activity=lab');await expect(page.locator('#lab-prepare')).toBeEnabled();await expect(page.getByTestId('lab-workspace')).toBeVisible();await capture('selection');
 const before=await commands();await page.locator('[data-lab-recipe=head]').click();await page.locator('[data-lab-recipe=input]').click();expect(await commands()).toEqual(before);
 await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();await capture('prepared');
 await page.locator('#lab-changed').fill('aaaa');await page.locator('#lab-changed').press('Tab');await expect(page.getByTestId('lab-refusal')).toContainText('exactly one');await capture('invalid');
 await page.locator('#lab-changed').fill('aaca');await page.locator('#lab-changed').press('Tab');await page.locator('#lab-run').focus();await page.keyboard.press('Enter');await capture('input-running');
 await expect(page.getByTestId('lab-result')).toContainText('Input abca → aaca');await page.getByTestId('lab-result').locator('h2').scrollIntoViewIfNeeded();await capture('input-result');await page.getByTestId('lab-result').locator('table').scrollIntoViewIfNeeded();await capture('input-distribution');await page.locator('.learn-exact summary').click();await capture('input-exact');const observed=await page.evaluate(()=>(window as any).labAudit.results.slice(-2));expect(observed[0].snapshots[0].id).toBe(observed[1].snapshots[0].id);expect(observed[0].trainingStep).toBe(observed[1].trainingStep);for(let i=0;i<4;i++){await expect(page.getByTestId('lab-result').locator('tbody tr').nth(i).locator('meter').nth(0)).toHaveAttribute('value',String(observed[0].probabilities[3][i]));await expect(page.getByTestId('lab-result').locator('tbody tr').nth(i).locator('meter').nth(1)).toHaveAttribute('value',String(observed[1].probabilities[3][i]));}
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);const action=(await page.locator('#lab-run').boundingBox())!;expect(action.height).toBeGreaterThanOrEqual(44);expect(action.x).toBeGreaterThanOrEqual(0);expect(action.x+action.width).toBeLessThanOrEqual(size.width);expect(action.y+action.height).toBeLessThanOrEqual(size.height);
 const stable=await commands();await page.locator('#lab-inspect-baseline').click();await expect(page.getByTestId('landmark-occurrence')).toHaveAttribute('data-position','3');expect(await commands()).toEqual(stable);await capture('input-world-source');await page.locator('#open-release-lab').click();await page.locator('#lab-explore').click();await page.locator('#open-release-lab').click();await expect(page.getByTestId('lab-result')).toContainText('Input abca');expect(await commands()).toEqual(stable);await capture('history-return');
 await page.locator('[data-lab-recipe=head]').click();await page.locator('#lab-head').selectOption('1');await capture('head-selection');await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();await capture('head-prepared');await page.locator('#lab-run').click();await capture('head-running');await expect(page.getByTestId('lab-result')).toContainText('Head 1 disabled');await page.getByTestId('lab-result').locator('h2').scrollIntoViewIfNeeded();await capture('head-result');await page.getByTestId('lab-result').locator('table').scrollIntoViewIfNeeded();await capture('head-distribution');await page.locator('.learn-exact summary').click();await expect(page.locator('.learn-exact')).toContainText('all positions');await capture('head-exact');
 await page.locator('[data-lab-recipe=update]').click();await capture('update-selection');await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();await capture('update-prepared');await page.locator('#lab-run').click();
 for(const state of ['p2_objective','p2_backward_trace','p2_gradient_contribution','p2_final_gradient','p2_adam_proposal','candidate_ready']){await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-canonical-state',state,{timeout:30_000});await capture(`update-${state}`);if(state!=='candidate_ready')await page.locator('#reverse-continue').click();}
 await page.locator('#execution-accept').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-outcome','accepted');await page.locator('#open-release-lab').click();await expect(page.getByTestId('lab-lineage')).toContainText('step 1');await expect(page.getByTestId('lab-result')).toContainText('accepted');await expect(page.getByTestId('lab-refusal')).toContainText('Prepare');await page.getByTestId('lab-result').locator('h2').scrollIntoViewIfNeeded();await capture('update-result');await page.getByTestId('lab-result').locator('table').scrollIntoViewIfNeeded();await capture('update-distribution');
 await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();await page.locator('#lab-run').click();
 for(const state of ['p2_backward_trace','p2_gradient_contribution','p2_final_gradient','p2_adam_proposal','candidate_ready']){await page.locator('#reverse-continue').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-canonical-state',state,{timeout:30_000});}await expect(page.locator('#execution-cancel')).toBeVisible();await page.locator('#execution-cancel').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-outcome','discarded');await page.locator('#open-release-lab').click();await expect(page.getByTestId('lab-lineage')).toContainText('step 1');await expect(page.getByTestId('lab-result')).toContainText('discarded');await page.getByTestId('lab-result').locator('h2').scrollIntoViewIfNeeded();await capture('update-discard-result');
 const end=await commands();await page.locator('#lab-workbench').click();await page.locator('#open-release-lab').click();await page.locator('#lab-learn').click();await page.locator('#open-release-lab').click();expect(await commands()).toEqual(end);
 await page.locator('details').filter({has:page.getByText('Completed results · retained session history',{exact:true})}).locator('summary').click();await page.locator('[data-lab-history="0"]').click();await expect(page.getByTestId('lab-result')).toContainText('Input abca');await capture('history');
 await writeFile(`${dir}/audit.json`,JSON.stringify(await page.evaluate(()=>(window as any).labAudit),null,2),{flag:'wx'});
});

for(const decision of ['accept','discard'])test(`chapter 5 ${decision} → Explore → Lab binds actual accepted lineage`,async({page})=>{
 test.setTimeout(120_000);await page.goto('/?experience=learn');await page.locator('#learn-predict').click();
 for(let i=0;i<10;i++)await page.locator('#short-continue').click();await page.locator('#short-teach').click();
 for(const state of ['p2_backward_trace','p2_gradient_contribution','p2_final_gradient','p2_adam_proposal','candidate_ready']){await page.locator('#reverse-continue').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-canonical-state',state,{timeout:30_000});}
 await page.locator(decision==='accept'?'#execution-accept':'#execution-cancel').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-canonical-state','tour_complete');
 const originalRun=await page.getByTestId('learn-orientation').getAttribute('data-run');await page.locator('#visitor-explore-toggle').click();await page.locator('#open-release-lab').click();await expect(page.getByTestId('lab-lineage')).toContainText(`step ${decision==='accept'?1:0}`);await expect(page.getByTestId('lab-lineage')).toContainText(decision==='accept'?'accepted':'discarded');
 await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();const dir=await evidenceDirectory(test.info());await page.screenshot({path:`${dir}/lineage.png`});
 await page.locator('#lab-run').click();await expect(page.getByTestId('lab-result')).toContainText('Input abca');
 if(decision==='accept'){await page.locator('[data-lab-recipe=update]').click();await page.locator('#lab-prepare').click();await page.locator('#lab-run').click();for(const state of ['p2_backward_trace','p2_gradient_contribution','p2_final_gradient','p2_adam_proposal','candidate_ready']){await page.locator('#reverse-continue').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-canonical-state',state,{timeout:30_000});}await page.locator('#execution-accept').click();await expect(page.locator('.spatial-shell')).toHaveAttribute('data-public-canonical-state','tour_complete');await page.locator('#open-release-lab').click();await expect(page.getByTestId('lab-lineage')).toContainText('step 2');await expect(page.getByTestId('lab-lineage')).toContainText('Chapter 5 recorded decision: accepted');await page.screenshot({path:`${dir}/historical-decision-after-Lab-update.png`});}
 await page.locator('#lab-learn').click();await expect(page.getByTestId('learn-orientation')).toHaveAttribute('data-run',originalRun!);await expect(page.getByTestId('learn-completion')).toContainText(decision==='accept'?'Acceptance succeeded':'Discard succeeded');await expect(page.getByTestId('learn-orientation')).toContainText('recorded decision');
});

test('Lab disposable input cancellation ignores late replies and preserves accepted state/history',async({page})=>{
 await page.addInitScript(()=>{const descriptor=Object.getOwnPropertyDescriptor(Worker.prototype,'onmessage')!,post=Worker.prototype.postMessage,delayed=new WeakSet();
 Worker.prototype.postMessage=function(m:any,...rest:any[]){if(m.command==='restore')delayed.add(this);return Reflect.apply(post,this,[m,...rest]);};
 Object.defineProperty(Worker.prototype,'onmessage',{configurable:true,get:descriptor.get,set(handler:(e:MessageEvent)=>void){const worker=this;descriptor.set!.call(this,(e:MessageEvent)=>{if(delayed.has(worker)&&e.data.status==='result')setTimeout(()=>handler(e),1500);else handler(e);});}});
 });
 await page.goto('/?experience=learn&activity=lab');await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();await page.locator('#lab-run').click();await expect(page.locator('#lab-cancel')).toBeVisible();await page.locator('#lab-cancel').click();
 await expect(page.getByTestId('status')).toContainText('cancelled');await page.waitForTimeout(1700);await expect(page.getByTestId('lab-result')).toHaveCount(0);await expect(page.getByTestId('lab-lineage')).toContainText('step 0');
 const dir=await evidenceDirectory(test.info());await page.screenshot({path:`${dir}/cancelled.png`});await page.locator('#clear-session').click();await expect(page.getByTestId('lab-workspace')).toHaveCount(0);await page.locator('#open-release-lab').click();await expect(page.getByTestId('lab-refusal')).toContainText('Prepare');
});

test('Lab input archival failure reports failure without publishing a result or altering accepted state',async({page})=>{
 await page.addInitScript(()=>{const w=window as any;w.failLab=false;const digest=crypto.subtle.digest.bind(crypto.subtle);crypto.subtle.digest=(...args:Parameters<SubtleCrypto['digest']>)=>w.failLab?Promise.reject(new Error('Controlled Lab archival failure')):digest(...args);});
 await page.goto('/?experience=learn&activity=lab');await page.locator('#lab-prepare').click();await expect(page.locator('#lab-run')).toBeEnabled();
 // Fail admission after the pre-execution reservation is allocated.
 await page.evaluate(()=>{const post=Worker.prototype.postMessage;Worker.prototype.postMessage=function(m:any,...rest:any[]){if(m.command==='restore')(window as any).failLab=true;return Reflect.apply(post,this,[m,...rest]);};});
 await page.locator('#lab-run').click();await expect(page.getByRole('alert')).toContainText('Controlled Lab archival failure');await expect(page.getByTestId('lab-result')).toHaveCount(0);await expect(page.getByTestId('lab-lineage')).toContainText('step 0');
 const dir=await evidenceDirectory(test.info());await page.screenshot({path:`${dir}/archival-failure.png`});
});
