import {test,expect} from '@playwright/test';import {mkdir,writeFile} from 'node:fs/promises';
import type {RunResult} from '../../app/worker/protocol.js';
const dir=process.env.SPATIAL_EVIDENCE_DIR??'/tmp/model-lab-wave1c-browser';
test('C01–C07 two real updates, source-bound learning and historical verification',async({page})=>{
 test.setTimeout(60000);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.addInitScript(()=>{const w=window as any;w.learnAudit={commands:[],results:[]};const send=Worker.prototype.postMessage,seen=new WeakSet();Worker.prototype.postMessage=function(message:any,...rest:any[]){w.learnAudit.commands.push(message);if(!seen.has(this)){seen.add(this);this.addEventListener('message',e=>{if(e.data.status==='result')w.learnAudit.results.push(e.data.result);});}return Reflect.apply(send,this,[message,...rest]);};});
 await mkdir(dir,{recursive:true});await page.setViewportSize({width:1920,height:1080});await page.goto('/?presentation=spatial');await expect(page.locator('#predict')).toBeEnabled();await page.locator('#document').fill('abca');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');
 const latest=()=>page.evaluate(()=>(window as any).learnAudit.results.at(-1)) as Promise<RunResult>;
 await page.locator('[data-world-parameter="wte"]').click();await page.locator('#parameter-row').selectOption('0');await page.locator('#parameter-column').selectOption('0');await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('1');const first=await latest();
 await expect(page.getByTestId('training-objective').locator('tbody tr')).toHaveCount(5);expect(Number(await page.getByTestId('training-mean').getAttribute('data-value'))).toBe(first.experiment!.objective.meanLoss);
 await page.locator('button[data-learning-stage="gradient"]').first().click();await page.locator('#learning-inspect-gradient').click();await expect(page.getByTestId('contribution-accounting')).toContainText('occurrences');
 const u=first.experiment!.update.parameters.find(p=>p.name==='wte'&&p.row===0&&p.column===0)!;expect(Number(await page.getByTestId('learning-gradient').getAttribute('data-value'))).toBe(u.gradient);
 await page.locator('#learning-expand').click();await expect(page.getByTestId('contribution-accounting')).toContainText('0 hidden');await page.waitForTimeout(300);await page.screenshot({path:`${dir}/gradient-1920x1080.png`});
 await page.locator('button[data-learning-stage="adam"]').first().click();await expect(page.getByTestId('adam-after')).toHaveAttribute('data-value',String(u.after));await expect(page.getByTestId('adam-delta')).toHaveAttribute('data-value',String(u.delta));await page.waitForTimeout(300);await page.screenshot({path:`${dir}/adam-1920x1080.png`});
 await page.locator('button[data-learning-phase="after"]').first().click();await page.locator('#learning-owner').first().click();
 for(const kind of ['q','mlpRelu','probabilities']){await page.locator('#spatial-operation').selectOption(kind);const a=first.run.artifacts.find(a=>a.kind===kind&&a.concept.token===4)!;await expect(page.getByTestId('forward-artifact')).toHaveText(a.id);expect(await page.getByTestId('forward-elements').locator('button').evaluateAll(es=>es.map(e=>Number(e.getAttribute('data-value'))))).toEqual(a.values);}
 await page.locator('button[data-learning-stage="compare"]').first().click();await expect(page.getByTestId('comparison-after-loss')).toBeVisible();await expect(page.getByTestId('comparison-pairs').locator('[data-before]')).toHaveCount(4);const paired=page.locator('[data-world-kind="probabilities"] [data-world-value]');await expect(paired).toHaveCount(8);expect(await paired.evaluateAll(es=>es.map(e=>Number(e.getAttribute('data-world-value'))))).toEqual([...first.runs[0].artifacts.find(a=>a.kind==='probabilities'&&a.concept.token===4)!.values!,...first.run.artifacts.find(a=>a.kind==='probabilities'&&a.concept.token===4)!.values!]);expect(new Set(await paired.evaluateAll(es=>es.map(e=>e.getAttribute('data-domain')))).size).toBe(1);await page.waitForTimeout(300);await page.screenshot({path:`${dir}/comparison-1920x1080.png`});
 await page.locator('#spatial-home').click();await page.waitForTimeout(300);await page.screenshot({path:`${dir}/learning-map-1920x1080.png`});await page.locator('[data-world-parameter="layer0.attn_wq"]').click();await page.locator('#parameter-row').selectOption('0');await page.locator('#parameter-column').selectOption('0');await page.locator('#spatial-current').click();await expect(page.locator('#spatial-learn')).toBeEnabled();await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('2');const second=await latest();
 await page.locator('button[data-learning-stage="adam"]').first().click();const q=second.experiment!.update.parameters.find(p=>p.name==='layer0.attn_wq'&&p.row===0&&p.column===0)!;expect(q.mBefore).not.toBe(0);await expect(page.getByTestId('adam-m-before')).toHaveAttribute('data-value',String(q.mBefore));await expect(page.getByTestId('adam-v-after')).toHaveAttribute('data-value',String(q.vAfter));await page.waitForTimeout(300);await page.screenshot({path:`${dir}/second-adam-1920x1080.png`});
 await page.locator('#spatial-experiment').selectOption(first.experiment!.id);await expect(page.locator('#spatial-learn')).toBeDisabled();await expect(page.getByTestId('spatial-live-step')).toHaveText('2');await page.locator('button[data-learning-stage="gradient"]').first().click();await page.locator('#learning-inspect-gradient').click();await expect(page.getByTestId('inspection-provenance')).toHaveText('VERIFIED RECOMPUTATION');await expect(page.getByTestId('learning-source')).toContainText(first.experiment!.trainingRunId);if(await page.locator('#learning-expand').textContent()==='Show bounded list')await page.locator('#learning-expand').click();await expect(page.getByTestId('contribution-accounting')).toContainText('2 hidden');await expect(page.getByTestId('learning-contributions').locator('tbody tr')).toHaveCount(3);await page.locator('#learning-expand').click();await expect(page.getByTestId('learning-contributions').locator('tbody tr')).toHaveCount(5);
 const oldQ=first.experiment!.update.parameters.find(p=>p.name==='layer0.attn_wq'&&p.row===0&&p.column===0)!;await page.locator('button[data-learning-stage="adam"]').first().click();await expect(page.getByTestId('adam-m-before')).toHaveAttribute('data-value',String(oldQ.mBefore));
 await page.setViewportSize({width:1280,height:720});await page.waitForTimeout(300);await page.screenshot({path:`${dir}/adam-1280x720.png`});await page.getByTestId("adam-after").scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/adam-endpoint-1280x720.png`});await expect(page.locator('.has-lens .selection-card')).toHaveCSS('padding','6px 10px');
 await page.locator('#spatial-current').click();await page.locator('button[data-learning-stage="compare"]').first().click();await page.waitForTimeout(300);await page.screenshot({path:`${dir}/comparison-1280x720.png`});await page.getByTestId("comparison-after-loss").scrollIntoViewIfNeeded();await page.screenshot({path:`${dir}/loss-comparison-1280x720.png`});
 for(const phase of ['before','training','after']){
  await page.locator('button[data-learning-phase="'+phase+'"]').first().click();await page.locator('#spatial-operation').selectOption('q');
  const expected=phase==='before'?second.runs[0]:phase==='training'?second.runs[1]:second.run;
  await expect(page.getByTestId('forward-artifact')).toHaveText(expected.artifacts.find(a=>a.kind==='q'&&a.concept.token===4)!.id);
  if(phase==='after')await expect(page.locator('#spatial-learn')).toBeEnabled();else await expect(page.locator('#spatial-learn')).toBeDisabled();
 }
 await page.locator('button[data-learning-stage="compare"]').first().click();await page.locator('#document').fill('abcb');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');await expect(page.locator('#spatial-experiment')).toHaveValue('');await expect(page.locator('[data-world-value][data-endpoint="before"]')).toHaveCount(0);await expect(page.getByTestId('spatial-live-step')).toHaveText('2');
 const fresh=await latest();await expect(page.getByTestId('forward-artifact')).toHaveText(fresh.run.artifacts.find(a=>a.kind==='q'&&a.concept.token===4)!.id);
 const audit=await page.evaluate(()=>(window as any).learnAudit);expect(audit.commands.filter((x:any)=>x.command==='train')).toHaveLength(2);expect(audit.commands.filter((x:any)=>x.command==='initialize')).toHaveLength(1);expect(errors).toEqual([]);
 await writeFile(`${dir}/learning-identities.json`,JSON.stringify({first:first.experiment,second:second.experiment,firstRun:first.run.manifest,finalRun:second.run.manifest,freshPrediction:fresh.run.manifest,commands:audit.commands.map((c:any)=>({command:c.command,sourceRunId:c.sourceRunId,sessionId:c.sessionId})),errors},null,2));
});
test('C10 accepted update remains explicit and inspectable when app archive admission fails once',async({page})=>{
 await page.addInitScript(()=>{let fail=false;const digest=crypto.subtle.digest.bind(crypto.subtle),send=Worker.prototype.postMessage;Worker.prototype.postMessage=function(m:any,...rest:any[]){if(m.command==='train')fail=true;return Reflect.apply(send,this,[m,...rest]);};crypto.subtle.digest=(...args:Parameters<SubtleCrypto['digest']>)=>{if(fail){fail=false;return Promise.reject(new Error('injected app archive admission failure'));}return digest(...args);};});
 await page.goto('/?presentation=spatial');await expect(page.locator('#predict')).toBeEnabled();await page.locator('#predict').click();await expect(page.locator('#spatial-learn')).toBeEnabled();await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('1');await expect(page.getByTestId('status')).toContainText('Accepted');await expect(page.locator('#spatial-experiment option')).toHaveCount(2);await page.locator('button[data-learning-phase="training"]').first().click();await expect(page.getByTestId('spatial-relationship')).toContainText('HISTORICAL');
});
test('C10 a late observed gradient reply cannot replace a newer selected transition',async({page})=>{
 await page.addInitScript(()=>{const w=window as any;w.held=[];w.hold=false;const send=Worker.prototype.postMessage,seen=new WeakSet();Worker.prototype.postMessage=function(m:any,...rest:any[]){if(!seen.has(this)){seen.add(this);const handler=this.onmessage;this.onmessage=e=>{if(w.hold&&e.data.status==='inspection'){w.held.push(()=>handler?.call(this,e));}else handler?.call(this,e);};}return Reflect.apply(send,this,[m,...rest]);};});
 await page.goto('/?presentation=spatial');await expect(page.locator('#predict')).toBeEnabled();await page.locator('#predict').click();await expect(page.locator('#spatial-learn')).toBeEnabled();await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('1');const first=await page.locator('#spatial-experiment').inputValue();await expect(page.locator('#spatial-learn')).toBeEnabled();await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('2');await page.locator('button[data-learning-stage="gradient"]').first().click();await page.evaluate(()=>(window as any).hold=true);await page.locator('#learning-inspect-gradient').click();await expect.poll(()=>page.evaluate(()=>(window as any).held.length)).toBe(1);await page.locator('#spatial-experiment').selectOption(first);await page.evaluate(()=>{const w=window as any;w.hold=false;w.held.forEach((f:any)=>f());});await expect(page.getByTestId('learning-source')).toContainText(first);await expect(page.getByTestId('inspection-provenance')).toHaveCount(0);await expect(page.getByTestId('spatial-live-step')).toHaveText('2');
});
