import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import type {RunResult} from '../../app/worker/protocol.js';
const directory=process.env.SPATIAL_EVIDENCE_DIR??'/tmp/model-lab-wave1b-browser';
test('B01–B09 complete source-bound forward route and contextual exploration over real HTTP',async({page})=>{
  test.setTimeout(60000);
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));
  await page.addInitScript(()=>{const w=window as any;w.forwardAudit={commands:[],results:[]};const send=Worker.prototype.postMessage,seen=new WeakSet();Worker.prototype.postMessage=function(message:any,...rest:any[]){w.forwardAudit.commands.push({command:message.command,sessionId:message.sessionId});if(!seen.has(this)){seen.add(this);this.addEventListener('message',e=>{if(e.data.status==='result')w.forwardAudit.results.push(e.data.result);});}return Reflect.apply(send,this,[message,...rest]);};});
  await mkdir(directory,{recursive:true});await page.setViewportSize({width:1920,height:1080});await page.goto('/?presentation=spatial');
  await expect(page.locator('#predict')).toBeEnabled();await page.locator('#document').fill('abca');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');
  const latest=()=>page.evaluate(()=>(window as any).forwardAudit.results.at(-1)) as Promise<RunResult>;
  const first=await latest();await page.locator('#spatial-query').selectOption('3');
  await page.screenshot({path:`${directory}/overview-1920x1080.png`});
  const kinds=['tokenEmbedding','positionEmbedding','embeddingSum','embeddingNorm','preAttentionNorm','q','k','v','attentionLogits','attentionProbabilities','headOutput','attentionOutput','attentionProjection','attentionResidual','preMlpNorm','mlpUp','mlpRelu','mlpDown','mlpResidual','logits','probabilities'];
  for(const kind of kinds){
    await page.locator('#spatial-operation').selectOption(kind);
    const token=['k','v'].includes(kind)?0:3,artifact=first.run.artifacts.find(a=>a.kind===kind&&a.concept.token===token&&(a.concept.head===undefined||a.concept.head===0))!;
    await expect(page.getByTestId('forward-artifact')).toHaveText(artifact.id);
    expect(await page.getByTestId('forward-elements').locator('button').evaluateAll(els=>els.map(e=>Number(e.getAttribute('data-value'))))).toEqual(artifact.values);
    await expect(page.locator('.context-lens')).toBeVisible();
  }
  await page.locator('#spatial-operation').selectOption('attentionProbabilities');await expect(page.getByTestId('softmax-terms').locator('tbody tr')).toHaveCount(4);
  await page.getByTestId('upstream-choices').getByRole('button',{name:/Attention scores/}).click();
  await page.getByTestId('upstream-choices').getByRole('button',{name:/K · key.*p0/}).click();await expect(page.getByTestId('forward-artifact')).toHaveText(first.run.artifacts.find(a=>a.kind==='k'&&a.concept.token===0)!.id);
  await page.locator('#spatial-operation').selectOption('headOutput');await expect(page.getByTestId('mixture-contributors').locator('tbody tr')).toHaveCount(4);await expect(page.getByTestId('mixture-rank')).toContainText('rank 3');await page.getByTestId('mixture-rank').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:`${directory}/mixture-1920x1080.png`});
  await page.locator('#spatial-operation').selectOption('attentionLogits');await page.locator('.geometry').scrollIntoViewIfNeeded();await page.waitForTimeout(300);await page.screenshot({path:`${directory}/attention-1920x1080.png`});
  for(const head of ['0','1']){await page.locator('#spatial-head').selectOption(head);await page.locator('#spatial-key').selectOption('4');await expect(page.getByTestId('spatial-unavailable')).toContainText('Future key');await expect(page.locator('[data-selected-key-edge],[data-selected-value-edge]')).toHaveCount(0);await page.locator('#spatial-key').selectOption('0');await expect(page.getByTestId('spatial-score')).toBeVisible();}
  await page.locator('#spatial-operation').selectOption('q');
  await page.locator('#spatial-head').selectOption('1');
  await expect(page.locator('.context-lens').getByText('All 8 components · selected [4]',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Inspect selected scalar',exact:true}).click();await expect(page.getByTestId('scalar-operation')).toBeVisible();
  const qValue=first.run.artifacts.find(a=>a.kind==='q'&&a.concept.token===3)!.values![4];
  expect(Number(await page.getByTestId('scalar-equation').locator('strong').getAttribute('title'))).toBe(qValue);
  await page.locator('#spatial-operation').selectOption('mlpRelu');await expect(page.getByTestId('forward-elements').locator('button')).toHaveCount(32);
  const before=first.run.artifacts.find(a=>a.kind==='mlpUp'&&a.concept.token===3)!.values!,index=before.findIndex(x=>x<0);
  await page.locator(`[data-forward-element="${index}"]`).click();await expect(page.getByTestId('relu-calculation')).toContainText('Local derivative = 0');await page.getByRole('button',{name:'Inspect selected scalar',exact:true}).click();await expect(page.getByTestId('scalar-operation')).toContainText('relu');await expect(page.getByTestId('inspection-state')).toContainText('ORIGIN OBSERVED');
  await page.waitForTimeout(300);await page.screenshot({path:`${directory}/relu-scalar-1920x1080.png`});
  const selected=await page.getByTestId('selected-world-object').textContent();await page.locator('#spatial-home').click();await expect(page.getByTestId('selected-world-object')).toHaveText(selected!);
  await page.locator('#waypoint-resume').click();await page.locator('#spatial-operation').selectOption('mlpDown');await expect(page.locator('#waypoint-status')).toContainText('detour');await page.locator('#waypoint-resume').click();await expect(page.locator('#spatial-operation')).toHaveValue('tokenEmbedding');
  await page.locator('#spatial-home').click();await page.locator('#spatial-focus').click();await page.locator('#zoom-in').click();const zoomed=await page.locator('#spatial-world').getAttribute('viewBox');await page.waitForTimeout(350);expect(await page.locator('#spatial-world').getAttribute('viewBox')).toBe(zoomed);
  await page.getByRole('button',{name:'Pan right',exact:true}).click();expect(await page.locator('#spatial-world').getAttribute('viewBox')).not.toBe(zoomed);await page.locator('#spatial-back').click();
  await page.locator('#spatial-world').focus();await page.keyboard.press('ArrowRight');
  const dragBox=await page.locator('#spatial-world').boundingBox();
  await page.mouse.move(dragBox!.x+dragBox!.width*.6,dragBox!.y+40);await page.mouse.down();await page.mouse.move(dragBox!.x+dragBox!.width*.6+60,dragBox!.y+70,{steps:4});await page.mouse.up();
  const beforeWheel=await page.locator('#spatial-world').getAttribute('viewBox');await page.mouse.wheel(0,-100);expect(await page.locator('#spatial-world').getAttribute('viewBox')).not.toBe(beforeWheel);
  await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#spatial-focus').click();const immediate=await page.locator('#spatial-world').getAttribute('viewBox');await page.waitForTimeout(100);expect(await page.locator('#spatial-world').getAttribute('viewBox')).toBe(immediate);await page.emulateMedia({reducedMotion:'no-preference'});
  await page.locator('#spatial-home').click();await page.waitForTimeout(300);
  for(const name of ['wte','wpe','layer0.attn_wq','layer0.attn_wk','layer0.attn_wv','layer0.attn_wo','layer0.mlp_fc1','layer0.mlp_fc2','lm_head'])await expect(page.locator(`[data-world-parameter="${name}"]`)).toHaveCount(1);
  await page.locator('[data-world-parameter="layer0.mlp_fc1"]').click();await expect(page.getByTestId('parameter-matrix').locator('tr')).toHaveCount(32);await page.locator('#parameter-row').selectOption('2');await page.locator('#parameter-output').click();await expect(page.locator('#spatial-operation')).toHaveValue('mlpUp');await expect(page.getByTestId('linear-terms').locator('tbody tr')).toHaveCount(8);
  await page.locator('#document').fill('abcabca');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('8 positions');await page.locator('#spatial-query').selectOption('7');await page.locator('#spatial-operation').selectOption('headOutput');await expect(page.getByTestId('mixture-contributors').locator('tbody tr')).toHaveCount(8);await expect(page.getByTestId('mixture-rank')).toContainText('fixed original components');
  await page.locator('#spatial-query').selectOption('0');await expect(page.getByTestId('mixture-contributors').locator('tbody tr')).toHaveCount(1);await expect(page.getByTestId('mixture-rank')).toContainText('rank 0');
  await page.locator('#spatial-query').selectOption('7');await page.locator('#spatial-operation').selectOption('mlpRelu');await page.getByRole('button',{name:'Inspect selected scalar',exact:true}).click();await expect(page.getByTestId('scalar-operation')).toBeVisible();
  await page.locator('#document').fill('abcb');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('5 positions');await expect(page.getByRole('alert')).toContainText('Selection unavailable');await expect(page.getByTestId('scalar-operation')).toHaveCount(0);
  await page.locator('#spatial-query').selectOption('4');await page.locator('#spatial-operation').selectOption('probabilities');const final=await latest();expect(final.run.manifest.runId).not.toBe(first.run.manifest.runId);await expect(page.getByTestId('forward-artifact')).toHaveText(final.run.artifacts.find(a=>a.kind==='probabilities'&&a.concept.token===4)!.id);
  const p=final.run.artifacts.find(a=>a.kind==='probabilities'&&a.concept.token===4)!.values!,vertices=[[1,1,1],[1,-1,-1],[-1,1,-1],[-1,-1,1]];
  expect((await page.locator('.context-lens [data-testid="simplex-point"]').getAttribute('data-coordinates'))!.split(',').map(Number)).toEqual([0,1,2].map(i=>p.reduce((s,v,j)=>s+v*vertices[j][i],0)));
  await page.waitForTimeout(300);await page.screenshot({path:`${directory}/output-1920x1080.png`});
  const count=await page.evaluate(()=>(window as any).forwardAudit.commands.length);await page.locator('#spatial-home').click();await page.locator('#spatial-back').click();await page.locator('#presentation-toggle').click();await page.locator('#presentation-toggle').click();expect(await page.evaluate(()=>(window as any).forwardAudit.commands.length)).toBe(count);
  await page.setViewportSize({width:1280,height:720});await page.locator('#spatial-home').click();await page.waitForTimeout(300);await page.screenshot({path:`${directory}/overview-1280x720.png`});await page.locator('#spatial-operation').selectOption('mlpRelu');await page.waitForTimeout(300);await page.screenshot({path:`${directory}/mlp-1280x720.png`});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true);
  const audit=await page.evaluate(()=>(window as any).forwardAudit);expect(audit.commands.filter((x:any)=>x.command==='initialize')).toHaveLength(1);expect(errors).toEqual([]);
  await writeFile(`${directory}/source-identity.json`,JSON.stringify({incoming:first.run.manifest,final:final.run.manifest,commands:audit.commands,errors},null,2));
});
