import {test,expect} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
const directory=process.env.SPATIAL_EVIDENCE_DIR??'/tmp/model-lab-wave1d';
test('D01–D05 source-bound explanations, interruption and static arithmetic',async({page})=>{
 test.setTimeout(90000);const errors:string[]=[];const wan:string[]=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:'))wan.push(r.url());});
 await page.addInitScript(()=>{const w=window as any;w.dAudit={commands:[],results:[]};const send=Worker.prototype.postMessage,seen=new WeakSet();Worker.prototype.postMessage=function(message:any,...rest:any[]){w.dAudit.commands.push(message.command);if(!seen.has(this)){seen.add(this);this.addEventListener('message',e=>{if(e.data.status==='result')w.dAudit.results.push(e.data.result);});}return Reflect.apply(send,this,[message,...rest]);};});
 await mkdir(directory,{recursive:true});await page.setViewportSize({width:1920,height:1080});await page.goto('/?presentation=spatial');await expect(page.locator('#predict')).toBeEnabled();await page.locator('#document').fill('abca');await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');
 const commands=()=>page.evaluate(()=>(window as any).dAudit.commands.filter((c:string)=>c!=='inspect'));
 const initial=await commands();await page.screenshot({path:`${directory}/overview-1920x1080.png`});
 await page.locator('#explanation-restart').click();await expect(page.getByTestId('explanation-status')).toContainText('1/21');
 await page.locator('#explanation-play').click();await expect(page.getByTestId('explanation-status')).toContainText('Playing');await page.locator('#explanation-play').click();await page.locator('#waypoint-next').click();await expect(page.locator('#spatial-operation')).toHaveValue('positionEmbedding');await page.locator('#waypoint-previous').click();
 await page.locator('#explanation-play').click();await page.locator('#spatial-operation').selectOption('mlpRelu');await expect(page.getByTestId('explanation-status')).toContainText('Explore');await expect(page.getByTestId('relu-calculation')).toContainText('max(0');await expect(page.getByTestId('forward-elements').locator('button')).toHaveCount(32);
 await page.locator('#waypoint-resume').click();await expect(page.locator('#spatial-operation')).toHaveValue('tokenEmbedding');
 await page.locator('#explanation-follow').uncheck();const box=await page.locator('#spatial-world').getAttribute('viewBox');await page.locator('#waypoint-next').click();expect(await page.locator('#spatial-world').getAttribute('viewBox')).toBe(box);
 await page.locator('#explanation-follow').check();await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#waypoint-resume').click();const immediate=await page.locator('#spatial-world').getAttribute('viewBox');await page.waitForTimeout(300);expect(await page.locator('#spatial-world').getAttribute('viewBox')).toBe(immediate);
 await page.locator('#spatial-world').focus();await page.keyboard.press('ArrowRight');await expect(page.getByTestId('explanation-status')).toContainText('Explore');
 const durations:number[]=[];for(let i=0;i<8;i++){const start=Date.now();await page.locator('#explanation-play').click();await page.locator('#explanation-play').click();await page.locator('#spatial-operation').selectOption('attentionLogits');await expect(page.getByTestId('qk-products').locator('tbody tr')).toHaveCount(4);await page.getByRole('button',{name:'Inspect selected scalar',exact:true}).click();await expect(page.getByTestId('scalar-operation')).toBeVisible();await page.locator('#waypoint-resume').click();durations.push(Date.now()-start);}
 expect(await commands()).toEqual(initial);
 for(const size of [{width:1920,height:1080},{width:1280,height:720}]){await page.setViewportSize(size);const tag=`${size.width}x${size.height}`;await page.locator('#spatial-home').click();await page.screenshot({path:`${directory}/overview-${tag}.png`});await page.locator('#spatial-operation').selectOption('attentionLogits');await page.locator('.geometry').scrollIntoViewIfNeeded();await page.screenshot({path:`${directory}/attention-${tag}.png`});await page.getByTestId('qk-products').scrollIntoViewIfNeeded();await page.screenshot({path:`${directory}/attention-products-${tag}.png`});await page.locator('#spatial-operation').selectOption('mlpRelu');await page.getByTestId('relu-calculation').scrollIntoViewIfNeeded();await page.screenshot({path:`${directory}/mlp-${tag}.png`});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true);}
 await page.locator('#explanation-route').selectOption('learning');await expect(page.locator('#explanation-play')).toBeDisabled();await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('1');await page.locator('#explanation-restart').click();await expect(page.getByTestId('training-objective')).toBeVisible();await page.locator('#explanation-play').click();await expect(page.getByTestId('explanation-status')).toContainText('2/5',{timeout:10000});await page.locator('#explanation-play').click();await page.locator('#learning-inspect-gradient').click();await expect(page.getByTestId('learning-contributions')).toBeVisible();await page.locator('#waypoint-resume').click();await page.locator('#waypoint-next').click();await expect(page.getByTestId('adam-gradient')).toBeVisible();await page.locator('#waypoint-previous').click();await expect(page.getByTestId('learning-contributions')).toBeVisible();await page.locator('#waypoint-next').click();
 for(const size of [{width:1920,height:1080},{width:1280,height:720}]){await page.setViewportSize(size);await page.locator('.lens-scroll').evaluate(el=>el.scrollTop=0);await page.screenshot({path:`${directory}/learning-${size.width}x${size.height}.png`});await page.getByTestId('adam-after').scrollIntoViewIfNeeded();await page.screenshot({path:`${directory}/learning-endpoint-${size.width}x${size.height}.png`});}
 await page.locator('#waypoint-next').click();await page.locator('#waypoint-next').click();await expect(page.getByTestId('comparison-pairs')).toBeVisible();const update1=await page.locator('#spatial-experiment').inputValue();await page.locator('#spatial-current').click();await page.locator('#spatial-learn').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('2');await page.locator('#spatial-experiment').selectOption(update1);await page.locator('#explanation-restart').click();await expect(page.getByTestId('spatial-live-step')).toHaveText('2');await page.locator('#waypoint-next').click();await page.locator('#waypoint-next').click();await expect(page.locator('.context-lens')).toContainText('Actual Adam · update 1');
 await page.locator('#explanation-play').click();await page.locator('#presentation-toggle').click();await page.locator('#presentation-toggle').click();await expect(page.getByTestId('explanation-status')).toContainText('Ready');await page.locator('#explanation-play').click();await page.locator('#document').fill('abcb');await expect(page.getByTestId('explanation-status')).toContainText('Ready');
 expect(await commands()).toEqual([...initial,'train','train']);
 expect(errors).toEqual([]);expect(wan).toEqual([]);await writeFile(`${directory}/audit.json`,JSON.stringify({durations,errors,wan,audit:await page.evaluate(()=>(window as any).dAudit)},null,2));
});

test('D lifecycle: hidden tab and delayed inspection cannot restart guidance',async({page})=>{
 await page.addInitScript(()=>{const w=window as any;w.held=[];w.hold=false;const send=Worker.prototype.postMessage,seen=new WeakSet();Worker.prototype.postMessage=function(m:any,...rest:any[]){if(!seen.has(this)){seen.add(this);const handler=this.onmessage;this.onmessage=e=>{if(w.hold&&e.data.status==='inspection')w.held.push(()=>handler?.call(this,e));else handler?.call(this,e);};}return Reflect.apply(send,this,[m,...rest]);};});
 await page.goto('/?presentation=spatial');await expect(page.locator('#predict')).toBeEnabled();await page.locator('#predict').click();await expect(page.locator('#spatial-learn')).toBeEnabled();await page.locator('#explanation-play').click();
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:true});document.dispatchEvent(new Event('visibilitychange'));});await expect(page.getByTestId('explanation-status')).toContainText('Explore detour');
 await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,value:false});document.dispatchEvent(new Event('visibilitychange'));});await page.waitForTimeout(6700);await expect(page.getByTestId('explanation-status')).toContainText('1/21');
 await page.locator('#waypoint-resume').click();await page.evaluate(()=>(window as any).hold=true);await page.getByRole('button',{name:'Inspect selected scalar',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).held.length)).toBe(1);
 await page.locator('#spatial-home').click();const box=await page.locator('#spatial-world').getAttribute('viewBox');await page.evaluate(()=>{const w=window as any;w.hold=false;w.held.forEach((f:any)=>f());});await expect(page.locator('.context-lens')).toBeHidden();await expect(page.getByTestId('scalar-operation')).toHaveCount(0);await page.waitForTimeout(350);const settled=await page.locator('#spatial-world').getAttribute('viewBox');await page.waitForTimeout(350);expect(await page.locator('#spatial-world').getAttribute('viewBox')).toBe(settled);expect(box).toBeTruthy();
 await page.locator('#explanation-play').click();await page.locator('#predict').click();await expect(page.getByTestId('status')).toContainText('Live prediction complete');await expect(page.getByTestId('explanation-status')).toContainText('Ready');
 await page.locator('#explanation-play').click();await page.locator('#clear-session').click();await expect(page.getByTestId('explanation-status')).toHaveCount(0);
});

test('D05 bounded repeated playback and inspection resource sample',async({page})=>{
 await page.goto('/?presentation=spatial');await expect(page.locator('#predict')).toBeEnabled();await page.locator('#predict').click();await expect(page.locator('#spatial-learn')).toBeEnabled();const cdp=await page.context().newCDPSession(page);const sample=async()=>{await cdp.send('HeapProfiler.collectGarbage');return {dom:await cdp.send('Memory.getDOMCounters'),heap:await cdp.send('Runtime.getHeapUsage')};};
 const batch=async()=>{for(let i=0;i<10;i++){await page.locator('#explanation-play').click();await page.locator('#explanation-play').click();await page.locator('#spatial-operation').selectOption('mlpRelu');await page.getByRole('button',{name:'Inspect selected scalar',exact:true}).click();await expect(page.getByTestId('scalar-operation')).toBeVisible();await page.locator('#waypoint-resume').click();}};
 await batch();const warm=await sample();const start=Date.now();await batch();const middle=await sample();await batch();const end=await sample();expect(end.dom.jsEventListeners).toBeLessThanOrEqual(middle.dom.jsEventListeners+10);expect(end.dom.nodes).toBeLessThanOrEqual(middle.dom.nodes+100);await mkdir(directory,{recursive:true});await writeFile(`${directory}/resources.json`,JSON.stringify({browser:page.context().browser()?.version(),procedure:'10 warmup cycles, then 2 × 10 play/pause/inspect/resume cycles; full GC before DOM/heap samples',elapsed20CyclesMs:Date.now()-start,warm,middle,end},null,2));
});
