"""Trusted MLP binding and strict supported-state reader; imported state is inert data."""
import hashlib
import json
import math
from pathlib import Path
import torch
from mlp import execute, initial_state, PARAMETERS

ROOT = Path(__file__).resolve().parent
PROFILE = 'mlp-f32-sgd-v1'
INTEGRATION = 'mlp-native-v1'


def digest(value):
    # JSON state hashes are generated by the TypeScript codec on admission; native
    # identity hashes exact source bytes, not Python's different number spelling.
    return 'sha256:' + hashlib.sha256(value).hexdigest()


def runtime():
    return digest(b''.join((ROOT / p).read_bytes() for p in ['mlp.py', 'adapter.py', 'fixtures.py']) + b''.join((ROOT.parent/'pythia'/p).read_bytes() for p in ['server.py','requirements.lock','dependencies.json']))


def exact(value, names):
    if not isinstance(value, dict) or set(value) != set(names):
        raise ValueError('Unexpected fields')


def f32(value):
    return type(value) in (int, float) and math.isfinite(value) and float(torch.tensor(value, dtype=torch.float32)) == value


def validate_state(state):
    exact(state, ['version', 'parameters', 'optimizer'])
    if state['version'] != 1: raise ValueError('State version')
    exact(state['parameters'], PARAMETERS)
    for name, sample in PARAMETERS.items():
        value = state['parameters'][name]
        if not isinstance(value, list) or len(value) != len(sample): raise ValueError('Parameter shape')
        if isinstance(sample[0], list):
            if any(not isinstance(row, list) or len(row) != len(sample[0]) or not all(map(f32, row)) for row in value): raise ValueError('Parameter float32 shape')
        elif not all(map(f32, value)): raise ValueError('Parameter float32')
    o = state['optimizer']
    exact(o, ['family', 'learningRate', 'momentum', 'step', 'schedule', 'datasetCursor', 'rngState'])
    if o['family'] != 'SGD' or o['learningRate'] != 0.0625 or o['momentum'] != 0 or o['schedule'] != 'constant' or o['rngState'] is not None: raise ValueError('Unsupported SGD state')
    if any(type(o[k]) is not int or not 0 <= o[k] <= 100000 for k in ['step', 'datasetCursor']): raise ValueError('State cursor')
    return state


def validate_request(r):
    exact(r, ['version','integration','profile','requestId','sessionId','epoch','action','input','state'])
    if r['version'] != 2 or r['integration'] != INTEGRATION or r['profile'] != PROFILE or r['action'] not in ['predict','train']: raise ValueError('Unsupported MLP request')
    for k in ['requestId','sessionId']:
        if not isinstance(r[k],str) or not 1 <= len(r[k]) <= 256: raise ValueError('Request identity')
    if type(r['epoch']) is not int or not 0 <= r['epoch'] <= 2**53-1: raise ValueError('Epoch')
    x=r['input'];exact(x,['kind','values','targets'])
    if x['kind'] != 'numeric': raise ValueError('Numeric input required')
    for key,width in [('values',2),('targets',1)]:
        rows=x[key]
        if not isinstance(rows,list) or not 1 <= len(rows) <= 16 or any(not isinstance(row,list) or len(row)!=width or not all(map(f32,row)) for row in rows): raise ValueError('Numeric input dimensions/float32')
    if len(x['values']) != len(x['targets']): raise ValueError('Target batch')
    if r['state'] is not None: validate_state(r['state'])
    return r


def capture(r):
    validate_request(r)
    torch.set_num_threads(1)
    starting=validate_state(r['state'] if r['state'] is not None else initial_state())
    observed,resulting=execute(r['input']['values'],r['input']['targets'],starting,r['action']=='train')
    points=[]
    for name,tensor in observed.items():
        parameter=name.split('.')[0] if name.split('.')[0] in PARAMETERS else None
        roles= (['hidden_feature','input_feature'] if parameter=='w1' else ['output_feature','hidden_feature']) if parameter and tensor.ndim==2 else (['hidden_feature'] if parameter=='b1' else ['output_feature']) if parameter else ['example','output_feature' if tensor.shape[-1:]==(1,) else 'input_feature' if name in ['inputs','input.gradient'] else 'hidden_feature'] if tensor.ndim==2 else []
        deps={'hidden.pre':['inputs','w1.before','b1.before'],'hidden':['hidden.pre'],'prediction':['hidden','w2.before','b2.before'], 'squared.error':['prediction','targets'],'loss':['squared.error'],'input.gradient':['loss'],'prediction.after':['inputs','w1.after','b1.after','w2.after','b2.after']}.get(name,[])
        if parameter and name.endswith('.gradient'): deps=['loss',parameter+'.before']
        if parameter and name.endswith('.after'): deps=[parameter+'.before']+([parameter+'.gradient'] if r['action']=='train' else [])
        if parameter and name.endswith('.delta'): deps=[parameter+'.before',parameter+'.after']
        phase='backward' if name.endswith('.gradient') else 'update' if name.endswith(('.after','.delta')) and parameter else 'post-update' if name=='prediction.after' else 'forward'
        semantics='Observed '+name+'. '
        if name=='loss':semantics+='Mean squared error: sum over every example and output feature divided by element count; no token objective.'
        if name.endswith('.delta'):semantics+='Representable after minus before; SGD uses before - 0.0625 * gradient, no momentum.'
        points.append({'id':name,'node':parameter or name,'port':name.split('.')[-1], 'invocation':'batch:0','phase':phase,'shape':list(tensor.shape),
          'axes':[{'role':role,'space':INTEGRATION+':'+role+(':'+parameter if parameter else ''),'size':size} for role,size in zip(roles,tensor.shape)],
          'dtype':'float32','encoding':'json-numbers-row-major','values':tensor.detach().flatten().tolist(),'origin':'observed','availability':'available',
          'source':{'file':'research/witnesses/mlp.py','symbol':'execute','revision':runtime()},'owners':[parameter] if parameter else [],'dependencies':deps,'semantics':semantics,'capabilities':['slice','source']})
    run={'version':2,'id':r['sessionId']+':'+r['requestId'],'integration':INTEGRATION,'definition':'numeric-mlp-2-3-1-v1','checkpoint':'state:starting','inputTransform':'numeric-f32-identity-v1','profile':PROFILE,'runtime':runtime(),'request':r,'execution':'native',
      'precision':{'storage':'float32','compute':'float32','policy':'CPU float32; comparison atol=1e-7 rtol=1e-6'},'input':r['input'],'points':points,
      'limits':['Deterministic fixture. One disposable SGD step; no server accepted state or automatic adoption. Starting and resulting supported state retained.','No randomness consumed; rngState null. No momentum or scheduler buffers. Scalar internals, arbitrary optimizers and mutations unsupported.']}
    return {'version':1,'codec':INTEGRATION,'record':{'run':run,'starting':starting,'resulting':resulting}}
