import type { BackwardReadModel } from "../presentation/backward-read-model.js";
import type { AdamReadModel } from "../presentation/adam-read-model.js";
import type { GuidedLearning } from "./guided.js";
import { escapeHtml } from "./evidence.js";
const n = (value: number | undefined) =>
  value === undefined
    ? "NOT CAPTURED"
    : Number(value.toPrecision(6)).toString();
const value = (v: number | undefined) =>
  `<span title="${v ?? "unavailable"}">${n(v)}</span>`;
export function learningView(
  backward: BackwardReadModel,
  adam: AdamReadModel,
  mode: "backward" | "adam",
  selectedEdge: number | undefined,
  compact: boolean,
  guided: GuidedLearning | undefined,
): string {
  const source = `<details class="learning-identity"><summary>Completed transition ${backward.step} → ${backward.step + 1} · source identity</summary><p>Experiment ${escapeHtml(backward.experimentId)}<br>Training run ${escapeHtml(backward.trainingRunId)}<br>Starting snapshot ${escapeHtml(backward.startingSnapshotId)}</p></details>`;
  const controls = `<nav class="learning-controls" aria-label="Completed transition inspection"><button id="show-backward" aria-pressed="${mode === "backward"}">Backward · complete</button><button id="show-adam" aria-pressed="${mode === "adam"}">Adam · completed update</button><button id="close-learning">Back to Attention</button></nav>`;
  const separate = guided
    ? `<p class="guided-context">Separate Guided context: ${(guided.before * 100).toFixed(1)}% → ${(guided.after * 100).toFixed(1)}% over ${guided.completed} real updates · ${escapeHtml(guided.document)}</p>`
    : "";
  const selected = backward.contributions.find(
    (edge) => edge.id === selectedEdge,
  );
  const body =
    mode === "backward"
      ? `<h2 tabindex="-1">BACKWARD · COMPLETE</h2><div class="objective-losses">${backward.positions.map((p) => `<div class="${p.public ? "public-loss" : ""}" data-position-loss="${p.position}"><span>${escapeHtml(p.prefix)} → ${escapeHtml(p.target)}</span><b>${value(p.loss)}</b>${p.public ? "<small>PUBLIC EXAMPLE</small>" : ""}</div>`).join("")}<div class="mean-objective"><span>Mean of ${backward.positions.length} losses</span><b>${value(backward.meanLoss)}</b></div></div><p>PUBLIC EXAMPLE ${escapeHtml(backward.positions.find((p) => p.public)?.prefix ?? "")} → ${escapeHtml(backward.positions.find((p) => p.public)?.target ?? "")} = 1 OF ${backward.positions.length} TRAINING POSITIONS · TRAINING OBJECTIVE: their mean loss.</p><div class="learning-layout"><div data-scroll-region="${mode}-state"><h3>Parameter stays fixed during backward</h3><div class="persistent-memory"><div>θ before<br>${value(backward.parameterBefore)}</div><div>Completed gradient<br><b data-testid="completed-gradient">${value(backward.gradient)}</b><small>ORIGIN OBSERVED</small></div></div><p>These are completed execution fields. Contributor display order is not arrival order.</p>${selected ? `<div class="contribution-equation" data-testid="selected-contribution"><h3>Edge ${selected.id} · operand slot ${selected.inputIndex}</h3><p>Incoming adjoint ${value(selected.childAdjoint)} × local derivative ${value(selected.localDerivative)} ≈ edge contribution ${value(selected.contribution)}</p></div>` : "<p>Select a captured operand occurrence to inspect its local chain-rule equation.</p>"}</div><div class="fan-in" data-scroll-region="backward-fan"><h3>Fan-in → Σ → completed gradient</h3><p class="graph-provenance" data-testid="backward-graph-state">ORIGIN ${backward.graphOrigin} · VERIFICATION ${backward.graphVerification} · RELATIONSHIP HISTORICAL</p>${backward.fanInAvailable ? `<p class="fan-sum" data-testid="fan-sum">Σ ${backward.contributions.length} captured contributions ≈ ${value(backward.sum)} · DERIVED<br>Completed parameter gradient ${value(backward.gradient)} · OBSERVED</p><table><thead><tr><th>Occurrence</th><th>Incoming adjoint</th><th>Local derivative</th><th>Contribution</th></tr></thead><tbody>${backward.visible.map((edge) => `<tr class="${selectedEdge === edge.id ? "selected-edge" : ""}"><td><button data-backward-edge="${edge.id}">Edge ${edge.id} · slot ${edge.inputIndex}</button></td><td>${value(edge.childAdjoint)}</td><td>${value(edge.localDerivative)}</td><td>${value(edge.contribution)}</td></tr>`).join("")}</tbody></table>${backward.hiddenCount ? `<p data-testid="hidden-subtotal">${backward.hiddenCount} additional contributions · subtotal ${value(backward.hiddenSubtotal)} · DERIVED</p>` : ""}<button id="toggle-fan-in">${compact ? "Show all contributors" : "Compact fan-in"}</button>` : "<p>Fan-in detail unavailable or verifying. The observed parameter gradient remains independently identified.</p>"}</div></div>`
      : `<h2 tabindex="-1">ADAM · completed parameter update</h2>${adam.availability === "AVAILABLE" ? `<div class="learning-layout"><div data-scroll-region="${mode}-state"><h3>Persistent parameter state</h3><div class="persistent-memory"><div>θ<br>${value(adam.update!.before)} → ${value(adam.update!.after)}</div><div>m · persistent<br>${value(adam.update!.mBefore)} → ${value(adam.update!.mAfter)}</div><div>v · persistent<br>${value(adam.update!.vBefore)} → ${value(adam.update!.vAfter)}</div></div><p>Completed gradient g = ${value(adam.update!.gradient)} · DIRECT</p><details><summary>Moment equations</summary><p>m after = β₁ m before + (1 − β₁) g<br>v after = β₂ v before + (1 − β₂) g²</p></details><h3>One-step result · same input</h3><p data-testid="one-step-result">${adam.beforeProbability === undefined ? "NOT CAPTURED" : (adam.beforeProbability * 100).toFixed(3) + "%"} → ${adam.afterProbability === undefined ? "NOT CAPTURED" : (adam.afterProbability * 100).toFixed(3) + "%"}</p><p class="completed-phases">PARAMETER COMMIT · COMPLETE<br>POST-UPDATE RERUN · COMPLETE</p>${separate}</div><div class="adam-calculation" data-scroll-region="adam-calculation"><h3>Transient calculation · bound starting optimizer</h3><p data-testid="adam-q" data-value="${adam.q}">q = αeff m̂ / (√v̂ + ε) ≈ ${value(adam.q)} · DERIVED</p><p>θ after = θ before − q</p><p data-testid="adam-delta" data-value="${adam.update!.delta}">Recorded delta = θ after − θ before ≈ ${value(adam.update!.delta)} · DIRECT</p><p>αeff = base LR × (1 − step / numSteps)<br>${value(adam.effectiveLearningRate)} ≈ ${value(adam.baseLearningRate)} × (1 − ${adam.step} / ${adam.numSteps})</p><p>β₁ ${value(adam.beta1)} · β₂ ${value(adam.beta2)} · ε ${value(adam.epsilon)}</p><p>Bias correction₁ = 1 − β₁^(step+1) ≈ ${value(adam.update!.biasCorrection1)}<br>Bias correction₂ = 1 − β₂^(step+1) ≈ ${value(adam.update!.biasCorrection2)}</p><p>m̂ = m after / correction₁ ≈ ${value(adam.update!.mHat)}<br>v̂ = v after / correction₂ ≈ ${value(adam.update!.vHat)}</p><details><summary>Raw transition values and identities</summary><pre>${escapeHtml(JSON.stringify(adam, null, 2))}</pre></details></div></div>` : "<p>NOT CAPTURED · this transition lacks its bound snapshots. Live optimizer state is not substituted.</p>"}`;
  return `<section class="learning-expansion" data-testid="learning-inspection" data-experiment="${escapeHtml(backward.experimentId)}" data-parameter="${backward.parameter.index}" data-learning-mode="${mode}">${controls}${source}${body}</section>`;
}
