import type { ForwardModel } from '../spatial/forward.js';
import { introductoryEvidence, predictionFeedback } from '../presentation/release-learning.js';
import { escapeHtml as esc } from './evidence.js';
import type { PublicTourState } from '../spatial/public-tour.js';

export function releaseIntroduction(f: ForwardModel | undefined, state: PublicTourState, requested: string, replay: boolean, busy: boolean, answer?: string): string | undefined {
  if (!['cold','p1_prediction_preview','p1_represent'].includes(state)) return undefined;
  const e = introductoryEvidence(f, requested);
  const chapter = state === 'cold' ? 'Opening' : state === 'p1_represent' ? '2 · Representation' : '1 · Prediction';
  const status = `<p class="learn-orientation" data-testid="learn-orientation" data-run="${esc(f?.runId ?? '')}">${chapter} · lesson p3 · ${replay ? 'Recorded replay · captured on opening · explanation only' : 'Fresh completed prediction'} · accepted parameters unchanged by navigation</p>`;
  const overview = `<nav class="learn-overview" aria-label="Computation overview"><span>Character + position</span><span aria-hidden="true">→</span><span>Mix earlier context</span><span aria-hidden="true">→</span><span>Transform & score</span><span aria-hidden="true">→</span><span>Next-token probabilities</span></nav><p class="learn-note">The world above expands these same operations. Values, Math and Source keep this run and occurrence.</p>`;
  if (state === 'cold') return status + `<h1>See how a model predicts what comes next</h1><p>Give a small model <strong>abca</strong>. At one position, it sees <strong>abc</strong> and assigns a probability to each possible next character. The example's known next character is <strong>a</strong>.</p><p>This teaching model has only a, b, c and a shared START/END marker. Its initialized weights let us inspect computation; they do not provide useful natural-language performance or established semantic circuits.</p>${overview}<p>Run a fresh prediction to begin, or enter Explore directly. Explanation and camera movement do not train the model.</p>`;
  if (!e.available) return status + `<h1>${state === 'p1_represent' ? 'How can the model calculate with a character and its position?' : 'What is the model predicting at this position?'}</h1><p role="status">${esc(e.reason)}</p>`;
  const stale = e.stale ? `<p class="learn-stale" role="status">Input edited to ${esc(requested)}. This lesson still shows recorded ${esc(e.document)}. Explicitly Predict to use the edited input.</p>` : '';
  if (state === 'p1_prediction_preview') return status + stale + `<h1>What is the model predicting at this position?</h1><dl class="learn-facts"><div><dt>Complete example / request</dt><dd data-testid="learn-example">${esc(e.document)}</dd></div><div><dt>Effective prefix at p${e.position}</dt><dd data-testid="learn-prefix">START → ${esc(e.prefix)}</dd></div><div><dt>Known target from the example</dt><dd data-testid="learn-target">${esc(e.targetLabel)}</dd></div><div><dt>Highest-probability output</dt><dd data-testid="learn-predicted">${esc(e.predictedLabel)}</dd></div></dl><p>p${e.position} follows character ${esc(e.character)}. The separate final position p${e.finalPosition} predicts the target ${esc(e.finalTarget)}.</p><table class="learn-probabilities" data-testid="learn-distribution" data-run="${esc(e.run)}" data-position="${e.position}"><caption>All ${e.rows.length} possible outputs · original probabilities · scale 0 to 100% · omitted mass 0</caption><thead><tr><th>Output</th><th>Probability</th><th>Meaning</th></tr></thead><tbody>${e.rows.map(row => `<tr data-output="${row.id}" data-value="${row.probability}"><th>${esc(row.label)}</th><td><span class="learn-bar-track"><span style="width:${row.probability * 100}%"></span></span><span>${(row.probability * 100).toFixed(2)}%</span></td><td>${row.target ? 'Known target' : ''}${row.target && row.predicted ? ' · ' : ''}${row.predicted ? 'Highest probability' : ''}</td></tr>`).join('')}</tbody></table><p>Prediction uses current parameters and does not train. A probability is neither a guarantee nor measured accuracy. No output is sampled here.</p><details class="learn-check"><summary>Optional check · what happened in this prediction?</summary><div role="group" aria-label="Understanding check"><button id="learn-check-next">Assigned next-token probabilities</button><button id="learn-check-guarantee">Guaranteed the top output</button><button id="learn-check-train">Trained the parameters</button></div><p role="status" data-testid="learn-feedback">${answer ? esc(predictionFeedback(e, answer)) : 'Choose an answer for an explanation, or continue without answering.'}</p></details>`;
  const labels = ['Character embedding lookup','Position representation lookup','Add component by component','Normalize the combined representation','Normalize again at the attention boundary'];
  return status + stale + `<h1>How can the model calculate with a character and its position?</h1><p>A token is an entry in the vocabulary. Here character <strong>${esc(e.character)}</strong> → vocabulary ID <strong data-testid="learn-token-id">${e.token}</strong>. The ID selects a row in the character embedding table; position <strong>${e.position}</strong> selects a row in the position table.</p><p>A vector is a list of numbers. Each component is one coordinate, measured on a signed scale with zero as its origin. Positive is not good and negative is not bad; these individual dimensions have no established human meanings. Initialized weights are not already trained representations.</p><ol class="learn-representation">${e.members.map((member,i) => `<li data-testid="learn-representation-member" data-kind="${member.kind}" data-artifact="${esc(member.artifact ?? '')}" data-run="${esc(e.run)}"><strong>${labels[i]}</strong><p>${member.values ? `Component [0]: <code data-value="${member.values[0]}">${member.values[0]}</code> · ${member.values.length} components, feature axis · observed float64` : 'Unavailable in this capture; no substitute values.'}</p></li>`).join('')}</ol>${e.members.slice(0,3).every(m => m.values) ? `<p class="learn-arithmetic" data-testid="learn-addition">Selected arithmetic [0]: ${e.members[0]!.values![0]} + ${e.members[1]!.values![0]} = ${e.members[2]!.values![0]} (observed sum).</p>` : ''}<p>Addition combines character and position information. RMS normalization rescales the list using all its components. This model performs two distinct initial normalizations; Math exposes each feature axis, epsilon 0.00001, original operands and result.</p><p>The first normalized stream is also saved for later residual addition. Its source remains available in detail. Next, the existing attention lesson explains how this position uses earlier context; that remaining curriculum has not been redesigned.</p>`;
}
