import { escapeHtml as esc } from './evidence.js';
import { learningNumber } from './release-learning.js';
import type { LabRecipe, LabBaseline } from '../presentation/release-lab.js';
export interface LabOutputRow { index:number; label:string; before:number; after:number; delta:number; }
export function releaseLabView(options: {recipe:LabRecipe; document:string; changed:string; position:number; head:number; baseline?:LabBaseline; acceptedStep:number;
  baselineStep?:number; baselineDetails?:unknown; chapterDecision?:string; refusal?:string; busy:boolean; result?:{label:string; rows:readonly LabOutputRow[]; exact:unknown; limitation:string; mean?:{before?:number; after?:number}}; history:readonly {label:string}[]; historyOffset:number; historyTotal:number;}) {
  const o=options, disabled=o.busy?'disabled':'', names={input:'Change one context character',head:'Disable one attention head',update:'Propose one training update'};
  const questions={input:'Does changing earlier context change the next prediction?',head:'What happens when one head stops contributing?',update:'How does one example change a later prediction?'};
  const fixed={input:'Complete model and optimizer state, character lookup, output meanings, position, numerical policy and runtime. Prediction does not train.',head:'Complete starting state, input, targets, capture budgets, numerical policy and runtime. The accepted model stays unchanged.',update:'The supported example, objective, native Adam policy and schedule. Only explicit Accept advances the current accepted state.'};
  const changes={input:`${o.document} → ${o.changed}`,head:`Layer 0 · head ${o.head}: output → zero before concatenation, across all covered positions`,update:'One provisional native Adam update; all declared trainable parameters receive proposals'};
  return `<section class="contextual-dock learn-dock lab-dock" data-testid="lab-workspace" aria-label="Experiment workspace" aria-busy="${o.busy}">
    <div class="dock-header"><div><strong>6 · Lab</strong><span>One controlled change</span></div><nav class="learn-actions" aria-label="Lab paths"><button id="lab-learn" ${disabled}>Learn</button><button id="lab-explore" ${disabled}>Explore</button><button id="lab-workbench" ${disabled}>Workbench</button></nav></div>
    <div class="dock-body"><h1>What changes when we change one thing?</h1><p>Choose a question. Prepare from your current accepted model, then Run explicitly.</p>
    <div class="lab-recipes" role="group" aria-label="Choose a controlled change">${(['input','head','update'] as const).map(r=>`<button id="lab-recipe-${r}" data-lab-recipe="${r}" aria-pressed="${o.recipe===r}" ${disabled}>${names[r]}</button>`).join('')}</div>
    <p data-testid="lab-lineage">Current accepted state: step ${o.acceptedStep}. Chapter 5 recorded decision: ${esc(o.chapterDecision??'none yet')} (historical).</p>
    <h2>${questions[o.recipe]}</h2><dl class="lab-contract"><dt>Baseline</dt><dd>${o.baseline?`${esc(o.baseline.document)} · accepted step ${o.baselineStep} at preparation · p${o.baseline.position}`:'Not prepared'}</dd><dt>Changed variable</dt><dd>${esc(changes[o.recipe])}</dd><dt>Held fixed</dt><dd>${fixed[o.recipe]}</dd></dl>
    ${o.baseline?`<details><summary>Prepared baseline identity and fixed execution conditions</summary><pre>${esc(JSON.stringify(o.baselineDetails,null,2))}</pre></details>`:''}<div class="lab-draft"><label>Example · 3–7 letters a, b, c<input id="lab-document" value="${esc(o.document)}" maxlength="7" ${disabled}></label>
    ${o.recipe==='input'?`<label>Changed example<input id="lab-changed" value="${esc(o.changed)}" maxlength="7" ${disabled}></label><label>Prediction position<input id="lab-position" type="number" min="0" max="${o.document.length}" value="${o.position}" ${disabled}></label><p data-testid="lab-prefix">Effective prefixes: START + ${esc(o.document.slice(0,o.position))} → START + ${esc(o.changed.slice(0,o.position))}. Changed character position: ${[...o.document].findIndex((c,i)=>c!==o.changed[i])+1} (first character is 1).</p>`:''}
    ${o.recipe==='head'?`<label>Supported head<select id="lab-head" ${disabled}><option value="0" ${o.head===0?'selected':''}>Layer 0 / head 0</option><option value="1" ${o.head===1?'selected':''}>Layer 0 / head 1</option></select></label><p>A head mixes information from earlier positions. Zeroing this output tests its contribution in this example; it does not establish universal importance or a learned specialization.</p>`:''}</div>

    ${o.refusal?`<p role="status" data-testid="lab-refusal">${esc(o.refusal)}</p>`:''}
    ${o.result?`<article data-testid="lab-result"><h2>${esc(o.result.label)}</h2>${o.result.rows.length?`<p data-testid="lab-interpretation">${o.result.rows.every(r=>r.delta===0)?'The complete output distribution is unchanged at this position. This is a valid measured outcome.':(()=>{const r=o.result!.rows.reduce((a,b)=>Math.abs(a.delta)>=Math.abs(b.delta)?a:b);return `Largest output change at this position: ${esc(r.label)} ${r.delta>0?'increased':'decreased'} by ${learningNumber(Math.abs(r.delta)*100)} percentage points. This describes this fixed example.`;})()}</p>`:''}${o.result.mean?`<p data-testid="lab-mean-loss">Whole-example mean loss: ${learningNumber(o.result.mean.before)} → ${learningNumber(o.result.mean.after)} · derived from all target probabilities; separate from selected-position output probability.</p>`:''}<p>Measured selected-position output probabilities · complete support · shared 0–100% scale. Change = result − baseline.</p><table><thead><tr><th>Output</th><th>Baseline</th><th>Changed</th><th>Change</th></tr></thead><tbody>${o.result.rows.map(r=>`<tr><th>${esc(r.label)}</th><td><meter min="0" max="1" value="${r.before}"></meter> ${learningNumber(r.before*100)}%</td><td><meter min="0" max="1" value="${r.after}"></meter> ${learningNumber(r.after*100)}%</td><td>${learningNumber(r.delta*100)} pp</td></tr>`).join('')}</tbody></table><p>${esc(o.result.limitation)}</p><details class="learn-exact"><summary>Exact Values / Math / Source and comparison evidence</summary><p>Original binary64 probabilities; delta is derived subtraction. Internal tensors are inspected separately by source run. No input-conditioned experiment receipt is invented.</p><pre>${esc(JSON.stringify(o.result.exact,null,2))}</pre><button id="lab-inspect-baseline" ${disabled}>Inspect baseline in this world</button><button id="lab-inspect-result" ${disabled}>Inspect changed result in this world</button></details><button id="lab-accepted" ${disabled}>View current accepted computation</button></article>`:''}
    <details><summary>Completed results · retained session history</summary><p>These comparison selections are presentation only. Retained runs and registered receipts remain evidence authorities. Showing ${o.historyTotal?o.historyOffset+1:0}–${Math.min(o.historyOffset+8,o.historyTotal)} of ${o.historyTotal} selections.</p><button id="lab-history-prev" ${o.busy||o.historyOffset===0?'disabled':''}>Earlier results</button><button id="lab-history-next" ${o.busy||o.historyOffset+8>=o.historyTotal?'disabled':''}>Later results</button>${o.history.map((r,i)=>`<button data-lab-history="${o.historyOffset+i}" ${disabled}>${esc(r.label)}</button>`).join('')||'<p>No completed Lab results yet.</p>'}</details>
    <p class="learn-note">Unchanged and worse outcomes are valid. One example does not establish general improvement. Selecting, editing, inspecting or returning never runs an experiment.</p></div>    <div class="lab-primary"><button id="lab-prepare" ${disabled}>Prepare fresh baseline</button><button id="lab-run" class="primary-action" ${o.busy||o.refusal?'disabled':''}>Run · ${names[o.recipe]}</button>${o.busy?'<button id="lab-cancel">Cancel experiment</button>':''}</div></section>`;
}
