import type { SpatialReadModel } from '../spatial/bindings.js';
import type { ForwardModel } from '../spatial/forward.js';
import { introductoryEvidence, predictionFeedback, forwardTourEvidence, forwardFeedback, releaseChapter, FORWARD_LESSON_STATES } from '../presentation/release-learning.js';
import { escapeHtml as esc } from './evidence.js';
import type { PublicTourState } from '../spatial/public-tour.js';
import type { ResolvedPublicTrainingDepthContext } from '../spatial/public-training-depth.js';

/** Readable precision changes text only. Nonzero values retain their sign and magnitude. */
export function learningNumber(value: number | undefined): string {
  return value === undefined ? 'unavailable' : Number(value.toPrecision(4)).toString();
}

export function trainingFeedback(answer: string): string {
  if (answer === 'sensitivity') return 'Yes: backward measures local sensitivity. Parameters change only after an optimizer proposal and successful explicit acceptance. A check click is not learning-validation evidence.';
  if (answer === 'update') return 'A gradient measures local sensitivity; Adam also uses persistent moments and a schedule. The gradient is not the applied update, and its sign does not guarantee a finite improvement.';
  return 'A lower loss here describes this fixed example. It does not establish improvement on other examples. Unchanged and worse outcomes are valid too.';
}

export function releaseTrainingChapter(ctx: ResolvedPublicTrainingDepthContext | undefined, state: PublicTourState,
  outcome?: string, decisionPending?: string, answer?: string, document = 'abca'): string {
  const n = (v: number | undefined) => `<strong data-value="${v ?? ''}">${learningNumber(v)}</strong>`;
  const parameter = ctx?.parameter;
  const witness = parameter ? `${parameter.name}[${parameter.row},${parameter.column}]` : 'unavailable parameter';
  const orientation = `<p class="learn-orientation" data-testid="learn-orientation" data-run="${esc(ctx?.gradientSourceRunId ?? '')}">5 · Learning and decision · ${esc(document)} · lesson p3 · ${state === 'tour_complete' ? `resolved: ${esc(outcome ?? 'unavailable')} · recorded decision` : 'accepted model unchanged · candidate provisional'}</p>`;
  const scope = `<p class="learn-note">One displayed parameter: ${esc(witness)}. The optimizer proposes changes for all ${ctx?.trainableParameterCount ?? 'declared'} trainable parameters, not just this witness.</p>`;
  let body = '';
  if (state === 'tour_complete' && outcome !== 'accepted' && outcome !== 'discarded') {
    body = '<h1>What state is authoritative?</h1><p role="status">Decision outcome unavailable. No acceptance or discard is claimed; reconcile authoritative state before another mutation.</p>';
  } else if (state === 'tour_complete') {
    body = `<h1>${outcome === 'accepted' ? 'What will later predictions use?' : 'What did discarding preserve?'}</h1><p data-testid="learn-completion">${outcome === 'accepted' ? 'Acceptance succeeded. That decision accepted the candidate parameters, optimizer state and schedule position. Later predictions use the current accepted state, including any further explicit training.' : 'Discard succeeded. That decision left the prior accepted parameters and optimizer state unchanged; the candidate was not applied.'}</p><p>The resolved comparison remains in Values, Math and Source. Enter Explore to inspect this computation, or open the workbench to try existing experiments.</p>`;
  } else if (!ctx?.available) {
    body = `<h1>How can this example change a later prediction?</h1><p role="status" data-testid="learn-training-unavailable">${esc(ctx?.reason ?? 'Waiting for bound training evidence.')} Missing evidence is not zero. No substitute computation was requested.</p>`;
  } else if (state === 'p2_objective') {
    const o = ctx.objective!, row = o.rows.find(r => r.position === 3);
    body = `<h1>How far is this prediction from the known answers?</h1><p>Prediction used the current model numbers. The example supplies a known next token at every position. Assigning less probability to a known answer gives more error, called <strong>loss</strong>.</p><p data-testid="learn-objective-scope">All ${o.rows.length} targets: ${o.rows.map(r => `p${r.position} → ${esc(r.targetLabel)}`).join(' · ')}. The training objective is their mean cross-entropy loss, including the final END target; p3 is only one part.</p><div class="learn-bound-result" data-testid="learn-objective-result"><p>Whole-example mean loss: ${o.observedMean === undefined ? 'measuring…' : n(o.observedMean)} · observed runtime result</p><p>Selected p3 → ${esc(row?.targetLabel ?? 'unavailable')}: target probability ${n(row?.probability)}; position loss ${n(row?.recordedLoss)} · observed, separate from the mean</p></div>`;
  } else if (state === 'p2_backward_trace') {
    body = `<h1>Which earlier calculations could affect the error?</h1><p>The error depends on the prediction, which depends on earlier calculations and model numbers. Working through those dependencies measures how sensitive the error is to a small change. This is <strong>backward computation</strong>.</p><div class="learn-bound-result">Whole-example objective → calculation dependencies → ${esc(witness)}<p>Dependency path: structural. Numerical adjoints ${ctx.numericAdjointsAvailable ? 'available in bound verified inspection' : 'unavailable in this retained detail context'}.</p></div><p>Text is not flowing backward. Forward execution is not being reversed, and parameters are not changing here.</p>`;
  } else if (state === 'p2_gradient_contribution') {
    const e = ctx.selectedContribution;
    body = `<h1>How does one use of a model number add to its sensitivity?</h1><p>A model number can affect the error through several uses. Each use adds a contribution to a running sensitivity total, called its <strong>gradient</strong>.</p><div class="learn-bound-result" data-testid="learn-contribution-result">${e ? `<p>One retained contribution: ${n(e.contribution)} · observed</p><p>Running total: ${n(e.before)} + ${n(e.contribution)} → ${n(e.after)} · observed partial accumulation</p>` : 'No matching retained contribution is available.'}</div><p>This is a retained subset, not a complete contribution history or arrival timeline. The partial total is not the completed gradient.</p>`;
  } else if (state === 'p2_final_gradient') {
    body = `<h1>What is this number’s total sensitivity?</h1><p>Backward computation has finished combining all uses of this parameter. The completed gradient measures the whole objective’s local sensitivity to this one model number.</p><div class="learn-bound-result" data-testid="learn-gradient-result">${esc(witness)} · completed gradient ${n(ctx.finalGradient)} · observed${ctx.backwardComplete ? ' · backward complete' : ' · backward incomplete'}</div><p>The retained subset is not summed to reconstruct this result. A gradient is not an applied update; its sign alone does not guarantee that a finite change will help.</p>`;
  } else if (state === 'p2_adam_proposal') {
    const u = ctx.proposal!;
    body = `<h1>What change does the optimizer propose?</h1><p>The optimizer combines sensitivity with remembered training history and the current step size. Here <strong>Adam</strong> uses persistent moments and a learning-rate schedule to propose new model numbers.</p><div class="learn-bound-result" data-testid="learn-proposal-result">${esc(witness)}: ${n(u.before)} → ${n(u.after)} · observed provisional values</div><p>This proposal is separate from accepted state. Math exposes the real moments, bias correction, learning rate and proposed value. Next, evaluate the candidate on the same example.</p>`;
  } else if (state === 'candidate_ready') {
    const c = ctx.candidate!, row = c.rows.find(r => r.position === 3)!;
    body = `<h1>Should this candidate change later predictions?</h1><p>The candidate has been evaluated separately on the same input and targets, with compatible model, runtime and numeric policy. It remains provisional until an explicit decision succeeds.</p><div class="learn-bound-result" data-testid="learn-candidate-result"><p>Same p3 occurrence → target ${esc(row.targetLabel)} · observed probabilities</p><p>Accepted baseline ${n(row.baselineTargetProbability)} → provisional candidate ${n(row.candidateTargetProbability)}</p><p>Whole-example mean loss: baseline ${n(c.baselineDerivedMean)} → candidate ${n(c.candidateDerivedMean)} · derived from all ${c.rows.length} target probabilities</p></div><p>Lower loss on this example does not establish general improvement. Unchanged or worse results remain valid. Accept changes accepted state only after success; Discard preserves the baseline.</p><p role="status" data-testid="learn-decision-status">${decisionPending ? `${esc(decisionPending === 'accepted' ? 'Acceptance' : 'Discard')} pending · awaiting authoritative acknowledgement` : 'Decision required · candidate not accepted'}</p>`;
  }
  return orientation + body + scope + `<details class="learn-check" ${answer && ['sensitivity','update','generalize'].includes(answer) ? 'open' : ''}><summary>Optional check · what can change the next prediction?</summary><div role="group" aria-label="Understanding check"><button id="learn-check-sensitivity">Backward measures sensitivity</button><button id="learn-check-update">Gradient is the applied update</button><button id="learn-check-generalize">Lower loss proves general improvement</button></div><p role="status" data-testid="learn-feedback">${answer && ['sensitivity','update','generalize'].includes(answer) ? esc(trainingFeedback(answer)) : 'Optional: choose an explanation, or continue. Clicks are not learning-validation evidence.'}</p></details>`;
}

export function releaseIntroduction(f: ForwardModel | undefined, state: PublicTourState, requested: string, replay: boolean, busy: boolean, answer?: string, model?: SpatialReadModel): string | undefined {
  if (FORWARD_LESSON_STATES.includes(state as typeof FORWARD_LESSON_STATES[number])) return releaseForward(model, state, requested, replay, answer);
  if (!['cold','p1_prediction_preview','p1_represent'].includes(state)) return undefined;
  const e = introductoryEvidence(f, requested);
  const chapter = releaseChapter(state);
  const status = `<p class="learn-orientation" data-testid="learn-orientation" data-run="${esc(f?.runId ?? '')}">${chapter} · lesson p3 · ${replay ? 'Recorded replay · captured on opening · explanation only' : 'Fresh completed prediction'} · accepted parameters unchanged by navigation</p>`;
  const overview = `<nav class="learn-overview" aria-label="Computation overview"><span>Character + position</span><span aria-hidden="true">→</span><span>Mix earlier context</span><span aria-hidden="true">→</span><span>Transform & score</span><span aria-hidden="true">→</span><span>Next-token probabilities</span></nav><p class="learn-note">The world above expands these same operations. Values, Math and Source keep this run and occurrence.</p>`;
  if (state === 'cold') return status + `<h1>See how a model predicts what comes next</h1><p>Give a small model <strong>abca</strong>. At one position, it sees <strong>abc</strong> and assigns a probability to each possible next character. The example's known next character is <strong>a</strong>.</p><p>This teaching model has only a, b, c and a shared START/END marker. Its initialized weights let us inspect computation; they do not provide useful natural-language performance or established semantic circuits.</p>${overview}<p>Run a fresh prediction to begin, or enter Explore directly. Explanation and camera movement do not train the model.</p>`;
  if (!e.available) return status + `<h1>${state === 'p1_represent' ? 'How can the model calculate with a character and its position?' : 'What is the model predicting at this position?'}</h1><p role="status">${esc(e.reason)}</p>`;
  const stale = e.stale ? `<p class="learn-stale" role="status">Input edited to ${esc(requested)}. This lesson still shows recorded ${esc(e.document)}. Explicitly Predict to use the edited input.</p>` : '';
  if (state === 'p1_prediction_preview') return status + stale + `<h1>What is the model predicting at this position?</h1><dl class="learn-facts"><div><dt>Complete example / request</dt><dd data-testid="learn-example">${esc(e.document)}</dd></div><div><dt>Effective prefix at p${e.position}</dt><dd data-testid="learn-prefix">START → ${esc(e.prefix)}</dd></div><div><dt>Known target from the example</dt><dd data-testid="learn-target">${esc(e.targetLabel)}</dd></div><div><dt>Highest-probability output</dt><dd data-testid="learn-predicted">${esc(e.predictedLabel)}</dd></div></dl><p>p${e.position} follows character ${esc(e.character)}. The separate final position p${e.finalPosition} predicts the target ${esc(e.finalTarget)}.</p><table class="learn-probabilities" data-testid="learn-distribution" data-run="${esc(e.run)}" data-position="${e.position}"><caption>All ${e.rows.length} possible outputs · original probabilities · scale 0 to 100% · omitted mass 0</caption><thead><tr><th>Output</th><th>Probability</th><th>Meaning</th></tr></thead><tbody>${e.rows.map(row => `<tr data-output="${row.id}" data-value="${row.probability}"><th>${esc(row.label)}</th><td><span class="learn-bar-track"><span style="width:${row.probability * 100}%"></span></span><span>${(row.probability * 100).toFixed(2)}%</span></td><td>${row.target ? 'Known target' : ''}${row.target && row.predicted ? ' · ' : ''}${row.predicted ? 'Highest probability' : ''}</td></tr>`).join('')}</tbody></table><p>Prediction uses current parameters and does not train. A probability is neither a guarantee nor measured accuracy. No output is sampled here.</p><details class="learn-check"><summary>Optional check · what happened in this prediction?</summary><div role="group" aria-label="Understanding check"><button id="learn-check-next">Assigned next-token probabilities</button><button id="learn-check-guarantee">Guaranteed the top output</button><button id="learn-check-train">Trained the parameters</button></div><p role="status" data-testid="learn-feedback">${answer ? esc(predictionFeedback(e, answer)) : 'Choose an answer for an explanation, or continue without answering.'}</p></details>`;
  const labels = ['Character embedding lookup','Position representation lookup','Add component by component','Normalize the combined representation','Normalize again at the attention boundary'];
  return status + stale + `<h1>How can the model calculate with a character and its position?</h1><p>A token is an entry in the vocabulary. Here character <strong>${esc(e.character)}</strong> → vocabulary ID <strong data-testid="learn-token-id">${e.token}</strong>. The ID selects a row in the character embedding table; position <strong>${e.position}</strong> selects a row in the position table.</p><p>A vector is a list of numbers. Each component is one coordinate, measured on a signed scale with zero as its origin. Positive is not good and negative is not bad; these individual dimensions have no established human meanings. Initialized weights are not already trained representations.</p><ol class="learn-representation">${e.members.map((member,i) => `<li data-testid="learn-representation-member" data-kind="${member.kind}" data-artifact="${esc(member.artifact ?? '')}" data-run="${esc(e.run)}"><strong>${labels[i]}</strong><p>${member.values ? `Component [0]: <code data-value="${member.values[0]}">${member.values[0]}</code> · ${member.values.length} components, feature axis · observed float64` : 'Unavailable in this capture; no substitute values.'}</p></li>`).join('')}</ol>${e.members.slice(0,3).every(m => m.values) ? `<p class="learn-arithmetic" data-testid="learn-addition">Selected arithmetic [0]: ${e.members[0]!.values![0]} + ${e.members[1]!.values![0]} = ${e.members[2]!.values![0]} (observed sum).</p>` : ''}<p>Addition combines character and position information. RMS normalization rescales the list using all its components. This model performs two distinct initial normalizations; Math exposes each feature axis, epsilon 0.00001, original operands and result.</p><p>The first normalized stream is also saved for later residual addition. Its source remains available in detail. Next, compare Query and Key to see how earlier positions contribute to this same prediction.</p>`;
}

function releaseForward(model: SpatialReadModel | undefined, state: PublicTourState, requested: string, replay: boolean, answer?: string): string {
  const e=forwardTourEvidence(model,requested);
  const orientation=`<p class="learn-orientation" data-testid="learn-orientation" data-run="${esc(model?.forward.runId??'')}">${releaseChapter(state)} · abca / p3 / layer 0 / head 0 / selected key p0 · ${replay?'Recorded replay':'Fresh completed prediction'} · explanation only</p>`;
  if(!e.available) return orientation+`<h1>Continue the recorded prediction</h1><p role="status">${esc(e.reason)}</p>`;
  const number=(v:number|undefined)=>v===undefined?'unavailable':`<code data-value="${v}">${v}</code>`;
  const vector=(v:readonly number[]|undefined)=>`[${v?.map(x=>number(x)).join(', ')??'unavailable'}]`;
  const member=(kind:string,label:string)=>{const x=e.get(kind);return `<section class="learn-operation" data-testid="learn-operation" data-kind="${kind}" data-artifact="${esc(x.artifact??'')}" data-identity="${esc(x.identity)}"><h2>${label}</h2><p>Captured float64 · ${x.values!.length} ${kind==='logits'||kind==='probabilities'?'output-index':'feature'} components · component [0]: ${number(x.values![0])}</p></section>`;};
  const projection=(kind:string)=>{const x=e.get(kind);return `<details><summary>Complete component [0] projection operands</summary><p>${esc(x.explanation.parameterName??'')} · no bias · all ${x.explanation.terms!.length} input components</p><p class="learn-scroll-note">All terms retained. On narrow screens, scroll this table horizontally for every column.</p><div class="learn-table-scroll" tabindex="0" role="region" aria-label="Complete arithmetic table · horizontal scroll"><table><thead><tr><th>Input feature</th><th>Input</th><th>Weight</th><th>Derived product</th></tr></thead><tbody>${x.explanation.terms!.map(t=>`<tr><th>${t.index}</th><td>${number(t.input)}</td><td>${number(t.weight)}</td><td>${number(t.product)}</td></tr>`).join('')}</tbody></table></div><p>Captured result: ${number(x.values![0])}. Products are derived from captured input and the compatible checkpoint; Math exposes the full operation.</p></details>`;};
  const check=(output=false)=>`<details class="learn-check" ${answer?'open':''}><summary>Optional check · ${output?'what is normalized?':'what do attention weights describe?'}</summary><div role="group" aria-label="Understanding check">${(output?['outputs','sample']:['positions','future','importance']).map(a=>`<button id="learn-check-${a}">${({outputs:'Possible next tokens',sample:'A sampled answer',positions:'Eligible positions mixing Values',future:'Includes the future p4',importance:'Proof of word importance'} as Record<string,string>)[a]}</button>`).join('')}</div><p role="status" data-testid="learn-feedback">${answer?esc(forwardFeedback(answer)):'Choose for an explanation, or continue without answering. Clicking does not establish comprehension.'}</p></details>`;
  const context=`<p class="learn-note" data-testid="learn-context">Complete request: <strong>abca</strong> · current position: <strong>p3 / c</strong> · effective prefix: <strong>START → abc</strong> · same recorded run and normalized representation as chapter 2.</p>`;
  const stale=e.intro.stale?`<p class="learn-stale" role="status">Input edited to ${esc(requested)}. This lesson still shows recorded abca. Explicitly Predict to use the edited input.</p>`:'';
  let body='';
  if(state==='p1_qkv') body=`<h1>How does earlier context affect this position?</h1><p>The normalized list of numbers from chapter 2 feeds three different learned projections. Query and Key supply numbers for comparison. Value supplies the numbers that will be combined after the comparisons become weights.</p><div class="learn-operation-grid">${['q','k','v'].map((kind,i)=>{const x=kind==='q'?e.q:kind==='k'?e.keys[0]!:e.values[0]!;return `<section class="learn-operation" data-kind="${kind}" data-artifact="${esc(x.artifact??'')}"><h2>${['Query at current p3','Key at START / p0','Value at START / p0'][i]}</h2><p>Distinct projection: ${esc(x.explanation.parameterName!)}. Input: normalized representation at ${kind==='q'?'p3':'p0'}.</p><p>Head 0's complete ${e.width}-component slice: ${vector(x.values!.slice(0,e.width))}</p></section>`;}).join('')}</div><p>Each eligible position has its own Key and Value. Vector dimensions have no established human meanings; these initialized heads are not demonstrated grammar or fact detectors. Next: compare p3 Query with p0 Key.</p>`;
  if(state==='p1_attention_compare') body=`<h1>Compare this position with eligible context</h1><p>A score measures a numerical comparison, not a probability. Multiply corresponding Query and Key components, add the signed products, then divide by the square root of this head's width.</p><ul class="learn-positions" data-testid="learn-positions">${e.positions.map(p=>`<li data-position="${p.position}" data-eligible="${p.eligible}">${esc(p.label)} · ${p.eligible?(p.position===3?'current · eligible':'earlier · eligible'):'future · excluded; no score coordinate'}</li>`).join('')}</ul><p>Eligibility is structural: the native loop compares only p0–p3. It did not materialize a future mask tensor or capture p4 as zero.</p><p class="learn-scroll-note">All terms retained. On narrow screens, scroll this table horizontally for every column.</p><div class="learn-table-scroll" tabindex="0" role="region" aria-label="Complete arithmetic table · horizontal scroll"><table data-testid="learn-dot"><caption>Selected comparison · layer 0 / head 0 / Query p3 / Key p0 · complete slices</caption><thead><tr><th>Head feature</th><th>Captured Query</th><th>Captured Key</th><th>Derived product</th></tr></thead><tbody>${e.lens.products!.map((product,j)=>`<tr><th>${j}</th><td>${number(e.lens.q![j])}</td><td>${number(e.lens.k![j])}</td><td>${number(product)}</td></tr>`).join('')}</tbody></table></div><p class="learn-arithmetic" data-testid="learn-score-arithmetic">Derived signed sum ${number(e.lens.sum)} ÷ √${e.width} (scale ${number(e.lens.scale)}) = ${number(e.lens.scaled)}. Captured score: ${number(e.lens.observedLogit)}.</p><p>Next: normalize the complete eligible score row.</p>${check()}`;
  if(state==='p1_attention_weights') {const h=e.heads[0]!,x=h.weights.explanation;body=`<h1>Turn comparison scores into position weights</h1><p>Softmax converts the complete score row into nonnegative weights whose sum is one. Here the alternatives are eligible positions, including START and the current position; they are not output characters.</p><p class="learn-scroll-note">All terms retained. On narrow screens, scroll this table horizontally for every column.</p><div class="learn-table-scroll" tabindex="0" role="region" aria-label="Complete arithmetic table · horizontal scroll"><table data-testid="learn-attention-row"><caption>Head 0 · all 4 eligible positions · captured scores and weights · omitted support 0</caption><thead><tr><th>Position / token</th><th>Raw score</th><th>Weight (0–100%)</th></tr></thead><tbody>${h.weights.values!.map((weight,k)=>`<tr><th>${esc(e.positions[k]!.label)}</th><td>${number(h.score.values![k])}</td><td><span class="learn-bar-track"><span style="width:${weight*100}%"></span></span>${number(weight)}</td></tr>`).join('')}</tbody></table></div><p>Derived stable normalization: subtract maximum ${number(x.maximum)}, exponentiate every eligible score, then divide by the full denominator ${number(x.denominator)}. Math exposes every exponential and original operand.</p><p>Next: use each weight to combine its position's Value vector. Weights alone do not prove causal word importance.</p>${check()}`;}
  if(state==='p1_value_mixture') {const x=e.heads[0]!.output.explanation;body=`<h1>Combine the Value numbers</h1><p>For one output component, multiply each eligible position's weight by that position's Value component. Add every signed contribution. The same operation combines each other component of this head's vector.</p><p class="learn-scroll-note">All terms retained. On narrow screens, scroll this table horizontally for every column.</p><div class="learn-table-scroll" tabindex="0" role="region" aria-label="Complete arithmetic table · horizontal scroll"><table data-testid="learn-weighted-values"><caption>Layer 0 / head 0 / output component [0] · all contributors · no omitted terms</caption><thead><tr><th>Position</th><th>Weight</th><th>Value [0]</th><th>Derived contribution</th></tr></thead><tbody>${x.points!.map((v,k)=>`<tr><th>${esc(e.positions[k]!.label)}</th><td>${number(x.probabilities![k])}</td><td>${number(v![0])}</td><td>${number(x.probabilities![k]!*v![0]!)}</td></tr>`).join('')}</tbody></table></div><p class="learn-arithmetic" data-testid="learn-mixture-sum">Complete derived sum: ${number(x.derivedReconstruction)} · captured head output [0]: ${number(x.observed)}.</p><p>Negative values remain negative contributions; zero remains zero. Positive is not good and negative is not bad. Values/Math show the original-space mixture and declared display projection. Next: join the distinct head vectors.</p>`;}
  if(state==='p1_attention_integration') body=`<h1>Join channels, project, then add the saved input</h1><p>Each head uses a different slice of the actual Query, Key and Value projections and produces its own ${e.width}-component vector. This is parallel numerical work, not evidence of learned specialization.</p><ol class="learn-integration"><li><h2>Concatenate: join the channels</h2><div data-testid="learn-heads">${e.heads.map(h=>`<p data-head="${h.head}">Head ${h.head} · projected channels ${h.head*e.width}–${(h.head+1)*e.width-1} → ${vector(h.output.values)}</p>`).join('')}</div>${member('attentionOutput','Joined vector')}<p>Joining preserves the components in head order. It does not add the head vectors together.</p></li><li>${member('attentionProjection','Transform the joined vector with the output projection')}${projection('attentionProjection')}</li><li>${member('attentionResidual','Add the saved representation')}<p data-testid="learn-attention-residual">Component [0]: projection ${number(e.get('attentionProjection').values![0])} + saved <strong>embeddingNorm</strong> ${number(e.get('embeddingNorm').values![0])} = captured ${number(e.get('attentionResidual').values![0])}. The saved input precedes preAttentionNorm; it is not the twice-normalized Query input.</p></li></ol><p>Next: normalize this context-aware result at the MLP boundary.</p>`;
  if(state==='p1_transform') body=`<h1>Transform the context-aware representation</h1><p>This model's MLP (a small network applied at this position) expands the list, changes each component with ReLU, and contracts it. Signs are numerical directions, not quality judgments. Other integrations can use different activations, normalization and residual structures.</p><ol class="learn-integration"><li>${member('preMlpNorm','Rescale at the MLP boundary')}<p>RMSNorm uses all ${e.get('preMlpNorm').values!.length} attentionResidual components and epsilon 0.00001. Its exact operands and scale are in Math.</p></li><li>${member('mlpUp','Expand with a no-bias projection')}${projection('mlpUp')}</li><li>${member('mlpRelu','ReLU: keep positive numbers, replace negative numbers with zero')}<details><summary>Every component before and after ReLU</summary><p class="learn-scroll-note">All terms retained. On narrow screens, scroll this table horizontally for every column.</p><div class="learn-table-scroll" tabindex="0" role="region" aria-label="Complete arithmetic table · horizontal scroll"><table data-testid="learn-relu"><thead><tr><th>Hidden feature</th><th>Captured expansion</th><th>Captured ReLU = max(0, x)</th></tr></thead><tbody>${e.get('mlpUp').values!.map((v,i)=>`<tr><th>${i}</th><td>${number(v)}</td><td>${number(e.get('mlpRelu').values![i])}</td></tr>`).join('')}</tbody></table></div></details></li><li>${member('mlpDown','Contract back to the representation width')}${projection('mlpDown')}</li><li>${member('mlpResidual','Add the correct saved context-aware input')}<p data-testid="learn-mlp-residual">Component [0]: contraction ${number(e.get('mlpDown').values![0])} + saved <strong>attentionResidual</strong> ${number(e.get('attentionResidual').values![0])} = captured ${number(e.get('mlpResidual').values![0])}. The saved source is before preMlpNorm.</p></li></ol><p>Next: project this final representation into one raw score per possible output.</p>`;
  if(state==='p1_score') body=`<h1>Score each possible next token</h1><p>The output projection (lm_head, with no bias) turns the final mlpResidual vector into one raw vocabulary score, called a logit, per output index. A score may be signed and is not a probability; only relative scores affect the next softmax.</p><table data-testid="learn-logits"><caption>Complete output-index space · captured float64 · no omitted indices</caption><thead><tr><th>Index / token</th><th>Raw score</th></tr></thead><tbody>${e.get('logits').values!.map((v,i)=>`<tr data-output-index="${i}"><th>${i} · ${esc(e.intro.rows[i]!.label)}</th><td>${number(v)}</td></tr>`).join('')}</tbody></table>${projection('logits')}<p>Index ${e.intro.rows.length-1} is the shared marker: START when it is an input at p0; END when it is a possible next output. Next: normalize all output scores.</p>`;
  if(state==='p1_probabilities'||state==='p1_complete') {const x=e.get('probabilities').explanation;body=`<h1>${state==='p1_complete'?'Back to the same recorded prediction':'How do those numbers become probabilities for possible outputs?'}</h1><p>Output softmax converts all vocabulary scores into nonnegative probabilities summing to one. No model execution is needed to navigate back to this result.</p><table class="learn-probabilities" data-testid="learn-distribution" data-run="${esc(e.run)}" data-position="3"><caption>All ${e.intro.rows.length} original output probabilities · 0–100% scale · omitted mass 0</caption><thead><tr><th>Output</th><th>Probability</th><th>Meaning</th></tr></thead><tbody>${e.intro.rows.map(r=>`<tr data-output="${r.id}" data-value="${r.probability}"><th>${esc(r.label)}</th><td><span class="learn-bar-track"><span style="width:${r.probability*100}%"></span></span>${(r.probability*100).toFixed(2)}%</td><td>${r.target?'Known target ':''}${r.predicted?'Highest probability':''}</td></tr>`).join('')}</tbody></table><details><summary>Full stable softmax denominator and original probabilities</summary><p>Derived maximum ${number(x.maximum)}; denominator Σ exp(logit − maximum) = ${number(x.denominator)} over every output index.</p>${x.exponentials!.map((v,i)=>`<p>Index ${i}: exp(score − max) = ${number(v)} · captured probability ${number(e.intro.rows[i]!.probability)}</p>`).join('')}</details><table data-testid="learn-normalizations"><thead><tr><th>Distribution</th><th>Alternatives</th><th>What it does</th></tr></thead><tbody><tr><th>Attention weights</th><td>Eligible positions START, p1, p2, p3</td><td>Combines Value vectors</td></tr><tr><th>Output probabilities</th><td>Possible next tokens a, b, c, END</td><td>Describes possible next outputs</td></tr></tbody></table><p data-testid="learn-endpoint">The known target after abc is <strong>${esc(e.intro.targetLabel)}</strong>. This run ranks <strong>${esc(e.intro.predictedLabel)}</strong> highest. No output was sampled. This is the original chapter 1 result, not a rerun or a trained improvement.</p>${check(true)}${state==='p1_complete'?`<p class="learn-handoff">Continue into the existing learning workflow with <strong>Start learning computation · propose one update</strong>. That explicit action begins computation for this example, leading to a provisional candidate and a separate accept/discard decision. Ordinary explanation navigation changes no parameters. Chapter 5 follows this error, sensitivity, proposal and explicit decision.</p>`:'<p>Next: return to the recorded prediction and choose whether to begin learning.</p>'}`;}
  return orientation+stale+context+body;
}
